### ISSUE TITLE
Matomo Bitnami Azure - Update PHP

### ISSUE THREAD

**Issue by ragalgut** [bitnami/vms#1013]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

none

### bndiagnostic was not useful. Could you please tell us why?

none

### Describe your issue as much as you can

Hello,

I have the following Bitnami image deployed in Azure:

Operating system: Linux (debian 11)
Image publisher: bitnami
Image offer: piwik
Image plan: 2-16

This image comes with a version of PHP 7.4.28. I need to upgrade to PHP 8 version, is it possible? What procedure do we have to follow to update the PHP version with an image managed by bitnami?

Thanks

**Comment by mdhont** [comment]
Bitnami applications come preconfigured and ready to use, and use their own components rather than relying on system components. As a result, it is not possible to update components individually. I recommend launching the latest Bitnami Matomo version and migrate the data there:

You can find relevant guides here:
https://docs.bitnami.com/aws/apps/matomo/administration/
