### ISSUE TITLE
[Bitnami Mattermost] <Documentation>

### ISSUE THREAD

**Issue by Crustified** [bitnami/vms#1029]
### Describe your suggestion as much as you can

The documentation at: [https://docs.bitnami.com/aws/apps/mattermost/administration/generate-configure-certificate-letsencrypt/](https://docs.bitnami.com/aws/apps/mattermost/administration/generate-configure-certificate-letsencrypt/)
would seem to be out of date - resulting in a failed installation.

In particular the lines:
sudo ln -sf /opt/bitnami/letsencrypt/certificates/DOMAIN.key /opt/bitnami/apps/mattermost/conf/certs/server.key
sudo ln -sf /opt/bitnami/letsencrypt/certificates/DOMAIN.crt /opt/bitnami/apps/mattermost/conf/certs/server.crt

refer to a directory structure which is not the same as the one that is shipped.

**Comment by gongomgra** [comment]
Hi @Crustified,

Thanks for using Bitnami. Please note `DOMAIN` is a pattern for your domain name. You will have to replace it with your current values for the link command to work. In case you are not sure about the file name, you can take a look at the certificates folder by running the next command

```
$ ls /opt/bitnami/letsencrypt/certificates/
```

**Comment by Crustified** [comment]
Yes. I am aware of that.
The /opt/bitnami/apps/mattermost/conf/certs/server.key is not the directory structure as shipped.

At this point we are probably not going to continue with Mattermost due to an entirely different issue.

**Comment by gongomgra** [comment]
Hi @Crustified,

The `/opt/bitnami/apps/mattermost/conf/certs/server.key` file is created by linking the `/opt/bitnami/apps/mattermost/conf/certs/DOMAIN.key` file into it. Did you run the `ln` command using the correct key file as input? 

I'm sorry to hear you are not going to use Mattermost at the end. Do not hesitate to ask any other questions you may have related to our solutions!

**Comment by AI-pha** [comment]
@gongomgra Sorry to reopen this issue, but I think @Crustified is right. The documentation is outdated.

I was still able to setup mattermost with ssl as follows:

The path for the nginx certs should be corrected in all relevant lines of the documentation by adding `bitnami/certs/`.
For instance:
`/opt/bitnami/nginx/conf/server.crt`   --> `/opt/bitnami/nginx/conf/bitnami/certs/server.crt`
The correct path is given [here](https://docs.bitnami.com/aws/apps/mattermost/administration/enable-https-ssl-nginx/).

The path for the mattermost certs doesn't exist anymore either.
Instead of linking the files into a specific different directory, I changed the `TLS Certificate File` and `TLS Key File` fields in `/opt/bitnami/mattermost/config/config.json`
This is described here: https://docs.mattermost.com/install/config-tls-mattermost.html#to-use-your-own-certificate

**Comment by gongomgra** [comment]
Hi @AI-pha,

Thanks for your message and for the detailed information. I have just created an internal task for our engineering and documentation teams to review this. We will post here any update.

**Comment by gongomgra** [comment]
Hi @Al-pha,

We have just updated our documentation site with the correct paths. Thanks for using our products!
