### ISSUE TITLE
[<Prestashop>] <IMAP not installed>

### ISSUE THREAD

**Issue by binaryatlas** [bitnami/vms#1065]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

52d2fc84-89a7-d3d2-c5c5-b2645f64ff53

### bndiagnostic output

 Resources: No issues found
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Apache: No issues found
    ✓ Php: No issues found
 

 
[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

not related

### Describe your issue as much as you can

I have a light sail instance on AWS with Prestashop. I get the error imap is not installed on this server. I have Gond though a lot of different possible fixes and none have worked. does bitnami have a way to install this PHP module?

**Comment by gongomgra** [comment]
Hi @binaryatlas,

Thanks for using Bitnami. We removed IMAP module from our PHP installations because it hasn't been maintained nor updated for a very long time (latest release is [from 2011](https://www.mirrorservice.org/sites/ftp.cac.washington.edu/imap/)). We recommend you to ask for an alternative to the Prestashop developers. Sorry for the inconveniences.

**Comment by phisher254** [comment]
> Hi @binaryatlas,
> 
> Thanks for using Bitnami. We removed IMAP module from our PHP installations because it hasn't been maintained nor updated for a very long time (latest release is [from 2011](https://www.mirrorservice.org/sites/ftp.cac.washington.edu/imap/)). We recommend you to ask for an alternative to the Prestashop developers. Sorry for the inconveniences.

hello there
is there a way to install it either way?
i have an application that needs php imap.

**Comment by gongomgra** [comment]
Hi @phisher254,

Thanks for your interest in using Bitnami. As mentioned in a previous post, we are no longer providing IMAP extension with our PHP runtime due to its lack of maintenance and security reasons. You would have to compile PHP source code on your own with IMAP support if you need that extension. Unfortunately, we can't provide you with support on this.

Sorry for the inconveniences.
