### ISSUE TITLE
AWS Lightsail - Bitnami WordPress - Site keeps going down intermittently

### ISSUE THREAD

**Issue by evanNMSG** [bitnami/vms#1113]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b8485e16-5a22-e56d-24e2-38236be282c3

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ✓ Wordpress: No issues found
    ? Apache: Found possible issues
    ✓ Php: No issues found

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3873 2541 640 112 692 980
Swap: 0 0 0
```
You could try to increase your instance's memory. Please check your cloud
provider's documentation for more information.
Press [Enter] to continue:

You can also enable swap memory to improve performance.

https://docs.bitnami.com/installer/faq/linux-faq/administration/increase-memory-linux/

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Wed Aug 23 16:36:46.256041 2023] [proxy_fcgi:error] [pid 3279:tid
139993207707392] [client **ip_address**:22440] AH01079: failed to make
connection to backend: httpd-UDS
 [Wed Aug 23 17:13:54.396386 2023] [authz_core:error] [pid 1449:tid
140693238335232] [client **ip_address**:52956] AH01630: client denied by server
configuration: /opt/bitnami/apache/cgi-bin
Press [Enter] to continue:
 [Wed Aug 23 18:24:04.222365 2023] [authz_core:error] [pid 1449:tid
140693288691456] [client **ip_address**:24170] AH01630: client denied by server
configuration: /opt/bitnami/apache/cgi-bin
```

### bndiagnostic was not useful. Could you please tell us why?

It was useful.

### Describe your issue as much as you can

Newspaper website going down intermittently. I have ~30 AWS Lightsail Instances running WordPress. This server, and its sister website on a separate Instance, are the only ones that have experienced this issue. Please advise.

**Comment by gongomgra** [comment]
Hi @evanNMSG,

Thanks for using Bitnami. Ligthsail instances are known to suffer performance issues due to the kind of those instances ([burstable instances](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-frequently-asked-questions-faq#amazon-lightsail-faq-instances)).

Apart from that, the bndiagnostic tool detected that your server memory is running out of free memory to start new processes and/or attend new requests. I'm afraid we don't have enough information to determine if this is caused due to any of the plugins or custom theme you have installed on your website, or simply due to the burstable instance itself. It looks like your issues are not caused by a bot attack according to the amount of requests attended from single IP addresses

```
-----------------------------------
Check number of lines of Apache access log
-----------------------------------
Running: wc -l access_log
In: /opt/bitnami/apache2/logs/

Output:

51160 access_log

-----------------------------------
Check performance issues: Count number of requests for the 10 most active IP addresses in the last 100.000 requests
-----------------------------------
Running: tail -n 100000 access_log | awk '{print $1}' | sort | uniq -c | sort -nr | head -n 10 | awk '{print $1}'
In: /opt/bitnami/apache2/logs/

Output:

1140
699
663
355
336
293
275
252
248
239
```

We recommend you to open a new question on how to debug the instance performance to the official AWS support team.
