### ISSUE TITLE
[WordPress] Memory Being Consumed

### ISSUE THREAD

**Issue by mbisque** [bitnami/vms#1130]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

57b2b324-1d60-7374-7775-fd556c1e2af4

### bndiagnostic was not useful. Could you please tell us why?

This seems over my head, need your professional advice

### Describe your issue as much as you can

I'm using an older Bitnami Wordpress stack and seeing that memory is being consumed over time which is a new phenomena in the last few months.

I've added more memory, but that does not look like a solution.

Short of migrating to the a new AWS instance with the most up-to-date bitnami stack, do have some recommendations/direction on how to diagnose or mitigate memory being consumed? I suspect a plug in and have disabled it and seeing if that helps.

**Comment by mdhont** [comment]
Some WordPress plugins consume lot's of resources. To troubleshoot the issue I recommend disabling them all and then enable them one by one to find the one to find the culprit.

**Comment by brianatbisley** [comment]
I had this problem several months ago.  I removed all of the plug ins that were not absolutely necessary and I still ran out of memory.  I moved to a T3 EC2 instance with absolutely stupid memory and it helped a lot but did not solve the problem.  After hours of parsing through error logs I found that there was a PHP error caused by one of my plug ins that caused apache to shut down and restart.  I reported this error to the plug in developer and they ignored it.  They told me it was just a 'warning'.  I went on their youtube channel and wrote several bad reviews of their product.  They eventually fixed it.
