### ISSUE TITLE
[Wordpress] Documentation issue with SSH

### ISSUE THREAD

**Issue by khparker** [bitnami/vms#1134]
### Describe your issue as much as you can

I find a discrepancy between various parts of the documentation.  [One (more generic) section](https://docs.bitnami.com/aws/faq/get-started/connect-ssh/) just reminds to make sure SSH is enabled in the AWS security group.  That's easy.

But the second part here (https://docs.bitnami.com/virtual-machine/faq/get-started/enable-ssh/) says "The SSH server is deactivated by default in Bitnami virtual machines... To activate the SSH server, execute the commands below at the server console:"

This is a bootstrapping problem: how am I supposed to get to a server console if SSH is disabled?  Either I'm missing something important earlier, or there's a gap in the documentation.

**Comment by jotamartos** [comment]
Hi @khparker,

The first link you posted is related to the AWS cloud instances but the second one is related to the local virtual machines. In the local VMs, the SSH server is disabled because you get access to the command line directly after launching the VM. In the case of a cloud instance, you need to ensure port 22 is open to be able to access the machine. Please ensure you are using https://docs.bitnami.com/aws/ when reading any guide in our documentation.

**Comment by khparker** [comment]
Ah!  Makes sense.  I will give it a try, but first: I see a zillion images when i search for bitnami-wordpress.  They are all debian, though the doc refers to ubuntu.   Have you just switched?

Also, any advice on filtering?  Is there a list of the image names somewhere else besides the EC2 console?  I ask because there are dozens of items that match bitnami-wordpress, but the console help on regular expression says to enable it by a method that doesn't actually appear in the console preferences.   I am looking for a standalone single instance using Ubuntu if possible.

**Comment by jotamartos** [comment]
>They are all debian, though the doc refers to ubuntu. Have you just switched?

We used Ubuntu in the past but we switched to Debian several years ago. Can you share the guides where you found the Ubuntu references? 

>Also, any advice on filtering? Is there a list of the image names somewhere else besides the EC2 console?

Please note that all community images are still published in the AWS platform and that's why you find that big amount of images. If you want to launch the latest one, please take a look at  this 

https://bitnami.com/stack/wordpress/cloud/aws/amis

or launch the latest available version in the AWS Marketplace 

https://aws.amazon.com/marketplace/pp/prodview-bzstv3wbn5wkq
