### ISSUE TITLE
Bitnami Wordpress - After migration website content has hrefs starting with ip address instead of domain in html code

### ISSUE THREAD

**Issue by rajasaad7** [bitnami/vms#1185]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

916edd30-9e01-5891-5710-e7092b49ace1

### bndiagnostic output

? Resources: Found possible issues
? Connectivity: Found possible issues
✓ Mariadb: No issues found
✓ Processes: No issues found
✓ Wordpress: No issues found
? Apache: Found possible issues
✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

I don't understand the complex response

### Describe your issue as much as you can

all the places where site has to call an image with href or it has the following code: "http://xxx.xx.214.xx/wp-content/uploads/2021/12/abc.png"

this is making the site to show some images but not other also at the logo of the website when it is clicked takes me to ip adress instead of mydomain.com

I tried to redirect Ip -> domain.com and its working fine if https version is requested it takes you to domain but when http version is called its not redirecting. 

is there a way or a place in database where i can replace this ip with my domain so in the html everywhere instead of ip there should be domain or replace http with https in the html when its rendered.

thanks in advance for any help

**Comment by gongomgra** [comment]
Hi @rajasaad7,

Thanks for using Bitnami. I see you have configured the WordPress domain in the `wp-config.php` file with HTTP protocol instead of HTTPS. We recommend you to update it to HTTPS so this value is consistent with Apache configuration and the HTTP to HTTPS redirect.

Apart from the above, if you still have some URLs configured with an IP address instead of the domain name, you will have to manually update them from the WordPress admin panel and/or the WordPress database. We highly recommend you to check this situation with the WordPress developers in case there is any other way to update them.

https://wordpress.org/support/forums/

Hope it helps!

**Comment by savionlee** [comment]
Click save without making changes on the perma link page to rebuild those. Then I had to relink the image on the page to call the new link instead of the old.

**Comment by gongomgra** [comment]
Hi @savionlee,

Thanks for your message. I understand you managed to fix your issue. Is that correct?
