### ISSUE TITLE
[Wordpress] Where can I find my SSL file

### ISSUE THREAD

**Issue by Barnabas2** [bitnami/vms#1194]
### Describe your issue as much as you can

I'm trying to create a BIMI DNS record as per this documentation: https://docs.aws.amazon.com/ses/latest/dg/send-email-authentication-bimi.html

To create the record, I need a URL that points to the SSL certificate of my domain but I don't know in which server directory I have to look and whether this directory on my server is publicly accessible. Could you please help me?

**Comment by jotamartos** [comment]
Hi @Barnabas2,

Certificates are usually stored inside the /opt/bitnami/apache/conf folder. We do not suggest you make that folder publicly available due to security concerns. However, you can create a symbolic link to your certificate using the `ln` command 

```
ln -sf /path/to/the/cert /opt/bitnami/wordpress/
```

This way, the cert will be available using yourdomain/certnamehere

Please note that the guide you posted is not maintained by us. Please contact AWS if you have any other questions about how to follow that guide.

**Comment by Barnabas2** [comment]
Hello @jotamartos,

This information helps. Thanks a lot.
