### ISSUE TITLE
Upgrade Bitnami SuiteCRM stack to 8.X

### ISSUE THREAD

**Issue by macknop** [bitnami/vms#1202]
### Describe your issue as much as you can

I have tried to set up a fresh install of SuiteCRM on an EC2 instances using Bitnami stack from AWS Marketplace.  Installs to 7.14 no problem, but can't upgrade to 8.X.  Filesize problems resolved, then all kinds of errors.  Is this doable? Will Bitnami be releasing an 8.X stack?

**Comment by gongomgra** [comment]
Hi @macknop,

Thanks for using Bitnami. We provide AWS images for SuiteCRM 8.x since some time ago. You can find them both in our website or in the AWS console

https://bitnami.com/stack/suitecrm/cloud

Regarding the upgrade process, you may be able to follow the official steps in the SuiteCRM docs about upgrades, having into account that upgrading base components like PHP, Apache or MySQL is not possible.

https://docs.suitecrm.com/admin/installation-guide/upgrading/

I think it would be easier to launch a new server with the upgraded version and migrate the SuiteCRM data there. Notice according to the official upgrade docs, there are some restrictions between the app version you can perform an upgrade. I'm afraid I don't know if these restrictions also apply to the app data, so I recommend you to open a new question in the official SuiteCRM forums before starting the upgrade or migration processes

https://community.suitecrm.com/

Hope it helps!
