### ISSUE TITLE
Wordpress - (www.example.com) Virtual Host Setting

### ISSUE THREAD

**Issue by marcus-sm8a** [bitnami/vms#1213]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

7bec6529-c645-8729-2c23-e5bd0e154cbc

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ? Resources: Found possible issues
    ? Processes: Found possible issues
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Sun Nov 05 03:48:30.739357 2023] [proxy_fcgi:error] [pid 11045:tid 
140207378454272] [client **ip_address**:39318] AH01071: Got error 'PHP message: 
PHP Notice: Unknown: file created in the system's temporary directory in Unknown 
on line 0'
```

### bndiagnostic was not useful. Could you please tell us why?

Not enough information about the Virtual Host ServerName information. 

### Describe your issue as much as you can

Hello Bitnami Wordpress - 

I am trying to find out some information about why the domain (www.example.com) that is entered by default in the vhosts file.

If running the Let's Encrypt Bitnami tools to set the SSL Certificate, this doesn't seem to change the Virtual Host "ServerName" name to the domain that you have requested from Lets Encrypt.  I am just curious about the entry below:

```
<VirtualHost 127.0.0.1:443 _default_:443>
  ServerName www.example.com
  ServerAlias *
  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/<hidden>.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/<hidden>.key"
```

Does the "ServerName" need/should match the SSL certificate? also this system is only running one domain, single site. 
The SSL is working fine with the lets encrypt certificate on 443 - we are also using an RDS database, so the local mariadb is disabled. 

I did do searching through the bitnami support pages for www.example.com and this seems to be the same in several users posts when they show their vhost file?? I could not see an answer, so should I just ignore it?

Does Bitnami Wordpress have a preferred apache setup if you only have one web site? 

Also not to sure how to fix the php notice that is listed in the output file..

Thanks for your help Bitnami

**Comment by jotamartos** [comment]
Hi @marcus-sm8a,

Thank you for using Bitnami. The Bitnami HTTPS configuration tool takes care of modifying the default ServerName in the Apache's conf file (/opt/bitnami/apache/conf/httpd.conf). As there is one single VirtualHost, it doesn't matter if you have "ServerName www.example.com" in the WordPress conf file or not because the "ServerAlias *" line will match with your domain. However, you can edit that file and set your domain name in the ServerName line so match with your configuration. You can learn more about these parameters in the [Apache's documentation](https://httpd.apache.org/docs/2.4/mod/core.html#servername).

Regarding the PHP error, you will need to investigate when that error happens (if when using a WordPress' plugin or when performing a specific action) and debug the issue. You will probably need to contact WordPress' or the plugin's developers to get more information.

**Comment by marcus-sm8a** [comment]
Hello Bitnami, 
Thanks for that update about the "ServerName" - and that link to the Apache Doc's this is helpful. 

I will investigate the php error with the plugin developers - thanks for sending me in the right direction.
