### ISSUE TITLE
[WordPress>] Restrict entire country IP Addresses via Apache, rather than Wordfence Plugin.

### ISSUE THREAD

**Issue by marcus-sm8a** [bitnami/vms#1219]
### Describe your issue as much as you can

Hello Bitnami, 

I am currently looking for a way to easily restrict access to the server via country, at the moment we are using a Wordpress Plugin called Wordfence, you can block countries at the wordpress level. 
But what I have noticed that these country IPs still get through the Apache side and are then blocked at the Wordfence level. 

I am reading up about using deny lists, but these lists seems very large in size, and not sure how it will affect response time, if you say for example want to block all IPs from china,russia & nk, as an example.  

Are you able to point me in the right direction when it comes to restricting Country IP traffic at the apache level? This VM is running at the moment on lightsail instances, which doesn't support WAF filtering like EC2.   

If I was to deny via IP in apache to support the bitnami configuration should I put the deny list in the "wordpress-https-vhost.conf" file? or do you suggest a better idea?  any ideas welcome :-) 

Thanks for your time 
Marcus

**Comment by jotamartos** [comment]
Hi, 

Thank you for using Bitnami. You would need to include your "deny list" in both wordpress-https-vhost.conf and wordpress-vhost.conf files. However, in order to not duplicate the information, you can use this line to include the information from [an external file ](https://stackoverflow.com/questions/10738320/apache-deny-from-list-of-ips-in-external-file)

```
Include /path/to/your/deny/list
```

This section in our documentation explains how to deny access to a group of IPs 

https://docs.bitnami.com/general/apps/wordpress-multisite/troubleshooting/deny-connections-bots-apache/

Instead of adding all "deny" lines there, you can include the external file as I mentioned above.

**Comment by marcus-sm8a** [comment]
Hello Bitnami, 

Thanks for your comments above, I am currently investigating your process listed above. :-) 

Thanks for your time as always. :-)
