### ISSUE TITLE
Bitnami package for Supabase does not work

### ISSUE THREAD

**Issue by kdamsmt** [bitnami/vms#1262]
### Describe your issue as much as you can

Hi,

I have install [Bitnami package for Supabase](https://bitnami.com/stack/supabase) through https://bitnami.com/stack/supabase/cloud/aws/amis after complete setup when I try to access Supabase dashboard by public IP it does work. I can't access to dashboard login.

<img width="994" alt="image" src="https://github.com/bitnami/vms/assets/17005582/a415d92f-4686-45a6-bb50-f564b7f407be">

**Comment by jotamartos** [comment]
Just a quick note to let you know that we found issues in the control scripts. We are working on a fix and will notify you when there is a new version available. Sorry for the inconvenience.

**Comment by KilianKae** [comment]
@jotamartos any progress on this? I tried to deploy on azure, and it seams to produce a similar issue:
[https://bitnami.com/stack/supabase/cloud/azure](https://bitnami.com/stack/supabase/cloud/azure)

**Comment by jotamartos** [comment]
We fixed the initialization but we found more issues when accessing the admin panel. We are working on it and expect to have a solution during the following weeks. Will ping you once we have more information.

**Comment by jotamartos** [comment]
Hi all, 

Sorry for the big delay in getting back to you. We finally finished with all the changes to make the solution work as expected and our pipeline is now working on releasing a new version of the solution. 

The main problem here was the configuration file at /opt/bitnami/supabase/.env. The ports to connect to Kong were not properly configured and that was creating connection issues. If you edit the file and set these parameters, you will be able to work with the UI

```
export STUDIO_PG_META_URL='http://localhost:8000/pg'
export SUPABASE_PUBLIC_URL='http://localhost:8000'
export SUPABASE_URL='http://localhost:8000/'
```

You will need to restart Supabase later for the changes to take effect.

```
sudo /opt/bitnami/ctlscript.sh restart supabase
```

The new version of Bitnami Supabase will include these changes by default. 

Please note that the studio port (4000) is not accesible by default. You will need to create a SSH tunnel to port 4000 and 8000 to work with the UI due to security reasons. 

![Screenshot 2024-04-25 at 16 41 58](https://github.com/bitnami/vms/assets/8791635/f4872e5a-18e8-4514-bef9-7824ccf70d68)

Please let us know if you have any doubt regarding how to use the API (port 8000) or the UI (port 4000)

Thanks.

**Comment by jotamartos** [comment]
Just a quick note to let you know that a new version of the VM with the changes mentioned above was released.
