### ISSUE TITLE
[WordPress] error: one or more domains had a problem  - check that a DNS

### ISSUE THREAD

**Issue by tuhairwed** [bitnami/vms#1278]
### Name and Version

WordPress packaged by Bitnami 6.4.1-6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

sudo /opt/bitnami/bncert-tool

### Are you using any custom parameters or values?

opt/bitnami/bncert-tool

### What is the expected behavior?

successful installation 

### What do you see instead?

[www.nilebreweries.com] acme: error: 400 :: urn:ietf:params:acme:error:dns ::
DNS problem: NXDOMAIN looking up A for www.nilebreweries.com - check that a DNS
record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for
www.nilebreweries.com - check that a DNS record exists for this domain

### Additional information

i cant install ssl

**Comment by tuhairwed** [comment]
guys this issue has been going on for weeks even after. dns changes. is anyone really going to help out or we look for other service providers

**Comment by jotamartos** [comment]
Please note that this is a lego/Let's Encrypt issue and it's not something related to Bitnami. As stated in the message, the A record is not properly configured and that's why the certificate can't be generated. Please ensure both www and non-www domains point to your IP before generating the SSL cert

https://www.whatsmydns.net/#A/www.nilebreweries.com

**Comment by tuhairwed** [comment]
Hello
I have got a certificate from a third party , can we try installing that

**Comment by jotamartos** [comment]
You can follow this guide to start using your certificates 

https://docs.bitnami.com/general/apps/wordpress/administration/enable-https-ssl-apache/
