### ISSUE TITLE
[WordPress - Apache] Install WordPress in a subdirectory

### ISSUE THREAD

**Issue by yuranoctavio** [bitnami/vms#130]
### Describe your issue as much as you can

Hey there.
I have a simple WordPress installation with my website working on Lightsail. Now I want to create a subdirectory for SEO purposes using the same instance to host a subsite for example, www.website.com/shop with its own database, I don't want to use WordPress Multisite. I tried to find tutorials showing how to do that but they are not clear.
Can someone help me with that? I'm new to Bitnami.

**Comment by jotamartos** [comment]
Hi @yuranoctavio ,

Thank you for your interest. We suggest you use a subdomain (shop.website.com) instead of using a new subdirectory and follow this guide to deploy your new application 

https://docs.bitnami.com/general/apps/wordpress-multisite/administration/create-custom-application-php/

Please note that you will need to set the ServerName and ServerAlias parameters in the Apache configuration to your new subdomain.

**Comment by yuranoctavio** [comment]
Hey @jotamartos thanks for replying.
I don't want to create a shop thats just an example. 
There isn't way to create a subdirectory with its own database?
I want to launch a project that require a subdirectory not a subdomain.

**Comment by jotamartos** [comment]
Yes, of course you can use a subdirectory. In this case, as you already have a WordPress app deployed in the instance, you will need to deploy your new app in a different directory and configure an "Alias" in Apache to redirect the requests to the subdirectory to that new deployment. 

https://stackoverflow.com/questions/38028047/create-apache-alias-in-2-4-7

We do not have any guide to configure the application this way, you will need to configure that new "Alias" and "Directory" block in the default VirtualHosts (/opt/bitnami/apache2/conf/vhosts/wordpress-vhost.conf and wordpress-https-vhost.conf files)
