### ISSUE TITLE
[WordPress] 404 error on all pages

### ISSUE THREAD

**Issue by ron0** [bitnami/vms#1318]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

3931e5f3-0ac1-de2a-742a-580fdbe7d730

### bndiagnostic output

    ✓ Apache: No issues found
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ✓ Mysql: No issues found
    ✓ Processes: No issues found
    ? Php: Found possible issues

### bndiagnostic was not useful. Could you please tell us why?

No specific help for my issue

### Describe your issue as much as you can

WordPress ceased functioning recently (within the last three days).  Only 404s are being returned.  Apache logs show the 404 error, but even the 404 page is not being rendered.

**Comment by jotamartos** [comment]
The site works for me now but the support tool warned you about these warnings in the PHP's log file 

----

[Php]

The following error appears in the /opt/bitnami/php/var/log/php-fpm.log:
```
[19-Dec-2023 13:37:25] WARNING: [pool www] server reached max_children setting (5), consider raising it

```
This error usually indicates PHP script execution is slow due to busy server resouces or buggy scripts. Please check the following guide to increase the number of PHP-FPM child processes:

https://docs.bitnami.com/general/apps/wordpress/configuration/configure-phpfpm-processes/

----

Please take a look at the documentation and the related tickets in this forum to resolve this issue.
