### ISSUE TITLE
Guacamole SFTP not working

### ISSUE THREAD

**Issue by haha150** [bitnami/vms#1404]
### Platform

Virtual Machine

### Describe your issue as much as you can

Hi, i tried to use SFTP with the guacamole version 1.5.4 that is your latest and it does not seem to work, the connection to my VM using RDP doesnt establish.

if i disable sftp then rdp works as usual. And this feature seems to work on older version. Any help?

**Comment by gongomgra** [comment]
Hi @haha150,

Thanks for using Bitnami. This issue is related to the Guacamole application itself as described in the official Guacamole Jira issue linked below

https://issues.apache.org/jira/browse/GUACAMOLE-1140

Please open a new question in the official Guacamole forums for further help on how to fix it.

**Comment by haha150** [comment]
Hi @gongomgra,

Thanks, seems like they resolved the issue and added a fix. Can you addnit to your version?

**Comment by gongomgra** [comment]
Hi @haha150,

Thanks for your message. Unfortunately, we can't apply the fix on our side to the current version. We usually wait for the upstream developers to release a new version including it. Our automated system will detect any new version released by Guacamole developers and release it (unless there is an internal error we need to check manually). Sorry for the inconveniences.
