### ISSUE TITLE
[<Bitnami Magento AWS>] I lost Sudo while trying to fix permissions

### ISSUE THREAD

**Issue by rukcus** [bitnami/vms#1405]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

I can't run SUDO to get this 

### bndiagnostic output

I can't run SUDO

### bndiagnostic was not useful. Could you please tell us why?

I can't run SUDO

### Describe your issue as much as you can

While trying to fix permissions on my bitnami Magento 2 installation I accidentally ran this command and now I lost sudo

sudo chown daemon:daemon -R /

Now I am getting this error:
bitnami@ip-172-31-34-120:~/stack/scripts$ sudo
sudo: /etc/sudo.conf is owned by uid 1, should be 0
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set

Is there a resource anyone can point me to to get sudo back?

I tried using su but the default bitnami password of passwd doesn't work.

**Comment by rukcus** [comment]
When I try to run

chown: changing ownership of '/etc/sudo.conf': Operation not permitted

**Comment by rukcus** [comment]
I still have an ssh terminal open but I'd lost the ability to connect to ftp.

**Comment by rukcus** [comment]
ls -l /usr/bin/sudo

daemon owns sudo

-rwxr-xr-x 1 daemon daemon 182600 Jan 14  2023 /usr/bin/sudo

**Comment by gongomgra** [comment]
Hi @rukcus,

Thanks for using Bitnami. I'm afraid it is not possible to update the filesystem permissions in your current server. You would need to mount the disk into another instance as a secondary disk, connect to that instance, mount the broken filesystem in a well-known directory, and finally fix the filesystem from there. Unfortunately, we can't provide you with help on this. You will need to find help in a more specialized forum. 

We recommend you to start a new instance and migrate the application data if possible, but I'm afraid I don't know if you would be able to backup your current application data due to your current instance status.

**Comment by rukcus** [comment]
If I were able to mount it as a second drive would it be a matter of just
fixing Sudo with the correct owner or is it many different ownerships for
different files?

**Comment by gongomgra** [comment]
Hi @rukcus,

I guess the wrong `chown` command changes many other files and directories in your filesystem (probably the whole filesystem) so I don't think fixing the `sudo` binary would be enough.
