### ISSUE TITLE
[minio>] Now websocket connection

### ISSUE THREAD

**Issue by ognif** [bitnami/vms#1410]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1fa9fd74-0b03-d9b5-9a10-f47269a6f6f7

### bndiagnostic was not useful. Could you please tell us why?

BEcause there is no real information

### Describe your issue as much as you can

I subscribe to AWS MArketplace Minio Server. Server was build successful and I was able to ssh to the server to get login/password for minio.
Minio Object Browser is accessable and login was successful 
Buckets are listed well.
Start browsing into the buckets will result is websocket errors. 
`objectBrowserWSMiddleware.ts:79 WebSocket connection to 'wss://minio.oft.btc-embedded.cloud/ws/objectManager' failed: 
(anonymous) @ objectBrowserWSMiddleware.ts:79
objectBrowserWSMiddleware.ts:180 Error in websocket connection. Attempting reconnection...`
I tried with delivered arn DNS and also with URL behind an AWS ALB with https. 
Both do not work.
It like ports are open well with security groups. Just the websockets are not working.

I think a marketplace subscription have to run well.

**Comment by gongomgra** [comment]
Hi @ognif,

Thanks for using Bitnami. Unfortunately, the bndiagnostic tool doesn't get any information out of Minio logs, and I don't see any error in the Apache logs. However, if buckets are properly listed, I understand the connectivity with AWS S3 service is ok, so the issue seems to be related the Minio application itself rather than to our installation. We recommend you to open a new question in the official Minio forums.

**Comment by ognif** [comment]
Sorry, but I have deleted the instance and cancelled the subscription. I have installed minio myself on our cluster and it works perfect. So finaly, you installation has bugs. However, because I do not want to pay money for not working managed services, I do not need further help. Thank you for your answer.

**Comment by gongomgra** [comment]
Hi @ognif,

Thanks for your message. I have created an internal task to review and fix this issue. We will update the thread with any new information.

**Comment by jamesshaw554** [comment]
Hello,
It seems you’re encountering issues with Minio’s WebSocket connections. Let’s troubleshoot this together.

Websocket Configuration:
Ensure that your load balancer (LB) allows WebSocket connections. If you’re using an AWS Application Load Balancer (ALB), make sure it’s configured to support WebSockets.
For an Nginx LB (proxy), you need to add the following lines to your configuration:
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";

These settings enable WebSocket support.
Minio Version:
Make sure you’re using a compatible Minio version. Upgrading to the latest version (e.g., RELEASE.2022-12-12T19-27-27Z) might resolve the issue.
Local Issue:
Since you mentioned that the Minio instance running at this link works fine, it’s likely a local issue.
Double-check your LB configuration and ensure that it allows HTTP upgrades for WebSockets.
Error Message:
The error message you provided (“Objects List unavailable. Please review your WebSockets configuration and try again”) indicates a problem with WebSocket communication.
Verify that your LB settings align with the requirements for Minio’s WebSocket connections.
Bucket Objects Not Showing:  [MyCenturaHealth Org
](https://www.mycenturahealth.com.co)If you encounter issues with bucket objects not showing, consider upgrading to the latest Minio version, as mentioned earlier.
Remember to check your LB settings and ensure WebSocket support. If you need further assistance, feel free to ask.
Best Regards
jamesshaw554

**Comment by hreyes** [comment]
![image](https://github.com/user-attachments/assets/48507150-6056-473f-a625-6dc7e08cb5e2)

Same problem in Azure

**Comment by munishpalmakhija** [comment]
I am also facing the same issue. Are there any updates or workarounds available?   @gongomgra ?

Thanks,
Munish

**Comment by gongomgra** [comment]
Hi all,

We have just released a new OVA image adding some extra configuration for the websocket connections. We are still in the process of releasing the rest of platforms. You can download the latest OVA at https://bitnami.com/stack/minio

Hope it helps!

**Comment by munishpalmakhija** [comment]
I have verified the new OVA and it works as expected.

**Comment by gongomgra** [comment]
@munishpalmakhija thank you for confirming it is working. We are closing this ticket as solved.
