### ISSUE TITLE
[wordpress] Unable to access site 503 errors

### ISSUE THREAD

**Issue by Yo5he** [bitnami/vms#1412]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

n/a

### bndiagnostic was not useful. Could you please tell us why?

It was useful but would not upload the diagnostic support bundle

### Describe your issue as much as you can

Cannot access the site.  503 error.  I need a secure link to upload the diagnostic support bundle.

**Comment by mdhont** [comment]
Could you explain more about the issues? 

The following guide might be of help:

https://docs.bitnami.com/aws/how-to/troubleshoot-wordpress-issues/

**Comment by Yo5he** [comment]
Can I send you the output from the diagnostic tool through here ?

**Comment by mdhont** [comment]
Could you run the bndiagnostic tool again and paste the output here?

**Comment by Yo5he** [comment]
It won't allow me to send the diagnostic file it says it's too large

**Comment by Yo5he** [comment]
[bitnami-wordpress-info-20240215-182907-1988.zip](https://github.com/bitnami/vms/files/14335750/bitnami-wordpress-info-20240215-182907-1988.zip)

**Comment by Yo5he** [comment]
@mdhont

**Comment by Yo5he** [comment]
@mdhont

**Comment by mdhont** [comment]
The bndiagnostic upload should work automatically, but could you paste the whole output of the tool?

**Comment by Yo5he** [comment]
That's the thing I'm getting the failed to upload error and it told me to
download the file which I sent in the previous message.

**Comment by Yo5he** [comment]
The diagnostic bundle file was successfully created, but the automatic upload to                      Bitnami servers failed. You will need to upload it to your Bitnami Support tick                     et manually. Please locate the following file in your file browser or in your te                     rminal: /tmp/bitnami-wordpress-info-20240222-134906-32116.zip Exercise caution w                     hen uploading the resulting diagnostic bundle to public sites as it contains det

**Comment by Yo5he** [comment]
this is the error I am getting also is there a way to direct message you?  As I have this customer down for more than 1 week

**Comment by mdhont** [comment]
I'm checking the data from the bndiagnostic output you've send earlier but it seems no useful info has been obtained. Could you check the available memory of your machine?

    free -m

And disk space:

    df -h

Also, could you check the apache log for errors?

    sudo cat /opt/bitnami/apache/logs/error_log

**Comment by sislay11** [comment]
A "503 Service Unavailable" error on a WordPress site generally indicates that the server hosting the website is temporarily unable to handle the request. Here are some steps you can take to troubleshoot and resolve the issue:

Check Server Status: Verify if there are any server outages or issues with the hosting provider. You can check the hosting provider's status page or contact their support for information.

Review Error Logs: Check the error logs on your server for more detailed information about what might be causing the 503 error. You can find these logs in the server's control panel or by accessing server files.

Plugin and Theme Issues: If you recently installed or updated a plugin or theme, it might be causing conflicts. Try deactivating plugins one by one to identify the problematic one. If you can't access the WordPress admin, you can deactivate plugins manually by accessing your site's files via FTP.

Theme Conflicts: Switch to a default WordPress theme (like Twenty Twenty-One) to see if the issue persists. This helps determine if the problem is related to the theme you're currently using.

Increase PHP Memory Limit: If your site is running out of memory, it can result in a 503 error. You can try increasing the PHP memory limit by adding the following line to your wp-config.php file:

Server Overload: If your server is overloaded due to a sudden surge in traffic, it might struggle to handle requests. Check your hosting plan and consider upgrading if necessary.

Server Configuration: Make sure your server configuration is set up correctly. Check with your hosting provider or server administrator to ensure all settings are optimized for WordPress.

Database Issues: A corrupted or overloaded database can also cause 503 errors. Consider repairing your WordPress database using tools like phpMyAdmin.

Caching Issues: Clear any caching mechanisms you have in place. This includes server-side caching, as well as caching plugins like W3 Total Cache or WP Super Cache.

Contact Hosting Support: If you've tried the above steps and the issue persists, it's advisable to contact your hosting provider's support. They can provide specific assistance based on their server configuration.
