### ISSUE TITLE
[WordPress] Bitnami Credentials Recover

### ISSUE THREAD

**Issue by baldawayash15** [bitnami/vms#143]
### Describe your issue as much as you can

Hi there,
I have a WordPress Bitnami installed from AWS. Currently I am not able to `cat bitnami_credentials` as the file is missing. Can you please suggest any other way to recover the application password?  Thanks in advance.

**Comment by jotamartos** [comment]
Hi @baldawayash15 ,

Thank you for using our solution. I just edited the title to match with the template we provide when you create a ticket, please take that into account for the future. 

If you do not know the default password we set when configuring the app, it'll be difficult to do anything because you won't be able to access the database either. It'd be way more easy if you configured the SMTP credentials in WordPress so you can send an email to reset the credentials. If that's not the case, you would need to reset the database root password first and then reset the WordPress' one. 

https://docs.bitnami.com/aws/apps/wordpress/administration/change-reset-password-mysql/
https://docs.bitnami.com/aws/apps/wordpress/administration/reset-wp-admin-password/

Please note that we do not provide 1:1 support, if you have any questions regarding the database or the app, please check its forums and documentation pages .
