### ISSUE TITLE
Bitnami - Error with Let's Encrypt

### ISSUE THREAD

**Issue by gentrad455** [bitnami/vms#1465]
### Describe your issue as much as you can

Hi, new to this but we are trying to enable https on an existing website on aws and wordpress.   Has been working fine with just http.   Trying to run sudo /opt/bitnami/bncert-tool and gets following error(s) while creating certificate:
The Bitnami HTTPS Configuration Tool will perform any necessary actions to your 
Bitnami installation. This may take some time, please be patient.

|

An error occurred creating certificates with Let's Encrypt:

2024/03/27 15:47:35 Could not create client: get directory at 
'https://acme-v02.api.letsencrypt.org/directory': Get 
"https://acme-v02.api.letsencrypt.org/directory": tls: failed to verify 
certificate: x509: certificate signed by unknown authority

**Comment by jotamartos** [comment]
Hi @gentrad455,

Please ensure you are using the latest version of the tool and try again to confirm if the issue was transient or not. 

https://docs.bitnami.com/general/how-to/understand-bncert/

If you continue running into issues, you can follow the alternative guide to generate the certificates 

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Comment by gentrad455** [comment]
Thanks for getting back to me.  I managed to get it working.   Had to setup DNS information.

Thanks,
Joe
