### ISSUE TITLE
[Joomla] How can I find the latest image with PHP-7?

### ISSUE THREAD

**Issue by madorian** [bitnami/vms#1468]
I tried to restore a JPA into Joomla-5, but I think it has some issues with PHP-8.

How can I find the last image that uses PHP-7?

I'm getting this error: 

```
PHP Fatal error:  Uncaught Error: Undefined constant "MB_OVERLOAD_STRING" in /bitnami/joomla/libraries/vendor/joomla/string/src/phputf8/utf8.php:38
```

**Comment by mdhont** [comment]
Bitnami images use the latest components and PHP-7 has reached EOL so it is not supported anymore.

**Comment by mdhont** [comment]
Yes that's possible. However, the format we have available for download is OVA and the earliest version is 3.10.11.

**Comment by madorian** [comment]
What is OVA - a format for VM? I can't just reference it in Docker, something like 
```
JOOMLA_IMAGE_TAG=bitnami/joomla-5-with-php-7
```

Also, what do you mean by earliest version 3.10.11. Is that Joomla 3.10.11 the latest image with PHP-7?

How do I search and find the tag I need to place in JOOMLA_IMAGE_TAG?

**Comment by mdhont** [comment]
Yes an OVA is a format for VM. Regarding the issue, Joomla uses PHP 8 since version 4. If you are using a container and you want to launch an earlier version you can do that by adding the right tag, which is 3.10.11-debian-11-r105 as you mention. If you experience any issues I recommend opening an issue here:

https://github.com/bitnami/containers/issues
