### ISSUE TITLE
Azure Bitnami solr image not started after image creation[<application>] <title>

### ISSUE THREAD

**Issue by rahularyatatva** [bitnami/vms#1471]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

a

### bndiagnostic was not useful. Could you please tell us why?

not able to start the server itself

### Describe your issue as much as you can

it is our prod , please help giving error after image creation giving vm is generalized.

Operation 'Start VM' is not allowed on VM 'diginext-solr' since the VM is generalized.

**Comment by gongomgra** [comment]
Hi @rahularyatatva,

Thanks for using Bitnami. Can you provide us with more information about your issue? According to this [support ticket](https://learn.microsoft.com/en-us/answers/questions/1191209/operation-start-vm-is-not-allowed-on-vm-since-the) in the official Microsoft community forums, I'd say your issue is more related to a modification done to your server than to the Bitnami installation itself. You can also get more information about generalized instances in the link below 

https://learn.microsoft.com/en-us/azure/virtual-machines/generalize

In order to discard an issue in our publishing process of the Solr image in Azure cloud, I have just launched a new Bitnami Solr machine and it has worked just fine. I have been able to SSH connect to the machine, as showed in the image below

![Screenshot 2024-04-03 at 16 28 25](https://github.com/bitnami/vms/assets/6660452/a93f97f6-8c49-414a-8b4f-91546676ff4f)
