### ISSUE TITLE
[WordPress] Clearly no longer supported and the existing documentation is close to useless.

### ISSUE THREAD

**Issue by ETN-A** [bitnami/vms#1473]
### Describe your suggestion as much as you can

Perhaps you could let people know that Bitnami Wordpress is incredibly buggy, it is no longer supported, and encourage people to not use it?

**Comment by jotamartos** [comment]
Hi @ETN-A,

Could you please let us know more information about why you say that the solution is buggy and not supported? Please note that we test all our solutions before making them public. We released the latest version of WordPress 6.5.0 yesterday and it's available in all the formats we package (containers, charts and VMs). They all include the latest version of MariaDB, PHP and Apache.

**Comment by ETN-A** [comment]
e.g. "https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/" is the suggested link to debug apache errors.

Half way down the page you get this:

`Startup Errors
Check the Apache error log file

Check the Apache error log file at /opt/bitnami/apache/logs/error_log for information about why the error occurred.

Check if another process is listening to that port`

What error? The page doesn't say.... What port? The page doesn't say.

`To see which process is already using that port you can run the following from a command prompt. Replace the PORT placeholder with the correct port number, such as 80 or 443.

sudo netstat -ltnp | grep PORT
In the last column you’ll see the process id or process name. You can then use:

ps aux | grep process_name
Look for the pid in the second column and you’ll get more information about that process.

In case another process is using that port, use another port or stop that process.`

Again "that port"... And all of that will make VERY little sense to the kind of user Bitnami Wordpress is aimed for.  

Or there is this: https://docs.bitnami.com/general/apps/wordpress/troubleshooting/deny-connections-bots-apache/

In our experience there are 1000s of connection from the IP address of our very own LightSail instance. Does the page help? Not at all. It then says:

`Edit the /opt/bitnami/apache/conf/vhosts/wordpress-vhost.conf and /opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf files:` But even if I did that (though I suspect it would be stupid to deny our own IP address?) it actually makes no difference editing those files! (Tried it with other IP addresses with no result).

Etc.

**Comment by jotamartos** [comment]
Hi @ETN-A,

You are talking about the bndiagnostic tool, not the Bitnami WordPress solution. 

The bndiagnostic tool is a tool we developed to get more information about your instance in case you run into issues and suggest changes based on the information it gets. In you case, it seems there is an error in Apache and that's why it suggest you checking the "debug errors" section in our documentation. The tool is not intelligent enough to know what's happening, it just suggest you what to do. You will need to review the log and confirm what the issue is.

Regarding the bots guide, as you mentioned, you should not blocked your own IP. However, it's interesting to know why your instance is generating that high number of requests. Maybe there is a plugin that is requesting your site so many times that is reducing the performance. You will need to evaluate that. You can also install security plugins like Wordfence to analyse your site to ensure there is no malicious code running there.

**Comment by Shepdesign** [comment]
Hello, I am getting the same error with the recent update on AWS. Now, all my WP htaccess docs cannot be edited?

**Comment by jotamartos** [comment]
Hi @Shepdesign,

what error are you getting? Did you take a look at this guide where we explain how to work with the htaccess files in the Bitnami WordPress solution?

https://docs.bitnami.com/general/apps/wordpress/administration/use-htaccess/

**Comment by Shepdesign** [comment]
Hey @jotamartos, so I noticed that with the update some of the folders moved locations? Before, I used to be able to access the Bitnami server via SSH and access the WP config file. Now, the WP config file seems to have moved it's file path because when I went to edit the config file in the original location, my server didn't read it. Once I updated a different config file within the opt/app/bitnami/wordpress/config or something like that.

Did file paths change with the recent update?

**Comment by jotamartos** [comment]
>Did file paths change with the recent update?

The paths were changed 3 years ago to unify the containers and VMs configuration. You can find now the WordPress' files at /opt/bitnami/wordpress (instead of /opt/bitnami/apps/wordpress/htdocs) and the Apache-related configuration files at /opt/bitnami/apache/conf/vhosts (instead of /opt/bitnami/apps/wordpress/conf). 

The documentation is updated and you shouldn't run into issues when following it.
