### ISSUE TITLE
bitnami-grafana | apache webserver appears tob e missing in bitnami-grafana-10.4.2-r0-debian-12-amd64.ova

### ISSUE THREAD

**Issue by artie-ontap** [bitnami/vms#1489]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

5999acf3-eca0-afd9-1a63-d44c3063e1f0

### bndiagnostic output

Server ports 22, 80 and/or 443 are not accessible.  Please check the following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

### bndiagnostic was not useful. Could you please tell us why?

bndiagnostic-tool was run interactively on the host - no firewall in config

### Describe your issue as much as you can

I am unable to access the grafana application within the deployed OVA.  When checking services using sudo /opt/bitnami/ctlscript.sh, no apache services are listed.  When further trying to troubleshoot, using ctlscript.sh -restart apache is unable to find the apache service.  The apache folder is missing under /opt/bitnami.  it appears teh apache web server is not installed in the OVA for three different OVA's I deployed - bitnami-grafana-10.4.1-r0-debian-12-amd64.ova, bitnami-grafana-10.4.1-r95-debian-12-amd64.ova, or  bitnami-grafana-10.4.2-r0-debian-12-amd64.ova.  How can i deploy apache to this appliance so that it will work with the grafana configuration in the bitnami grafana VM?  Thank you!

**Comment by gongomgra** [comment]
Hi @artie-ontap,

Thanks for using Bitnami. It is true that our Grafana solutions do not include the Apache webserver, but it is because Grafana includes its own webserver running at port 3000. You can get more information on the default port configuration in the link below

https://docs.bitnami.com/virtual-machine/infrastructure/grafana/get-started/understand-default-ports/

Apart from the above, we have detected our [docs website](https://docs.bitnami.com/virtual-machine/infrastructure/grafana/) for Grafana includes mentions to Apache server and other services not included in the image like Redis. I will open an internal task to update the docs.

**Comment by artie-ontap** [comment]
ah - thank you!  I was so confused :-)

**Comment by artie-ontap** [comment]
FYI - I got it all figured out - thank you for your help and for suggesting the doc updates!  I thought I was going crazy :-)
