### ISSUE TITLE
[Bitnami] <Frappe CRM>

### ISSUE THREAD

**Issue by GranColombianoDeAlemania** [bitnami/vms#1635]
### Describe your suggestion as much as you can

Hello Together, I would like to suggest Frappe CRM to be introduced as a .ova application in Bitnami. It's a super light and easy CRM with Email, WhatsApp and Phone integration.
 I am a total noob in anything in regards of VM, Network etc. but with Bitnami I managed to use acouple of great apps. Thanks for the good work.

**Comment by gongomgra** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; due to limited resources, this process could take some time. In the meantime and to prevent the stale bot from closing this issue, we will add the 'on-hold' label.

In the meantime, you can use our ERPNext solutions, which include the Frappe CRM framework already installed.

https://bitnami.com/stack/erpnext

**Comment by carrodher** [comment]
Hi, unfortunately, after an internal review and due to other priorities, this solution was not considered for inclusion in the catalog in the short/mid-term.

We apologize for the inconvenience. We will be sure to reconsider it in the future.

Thanks for your suggestion!
