### ISSUE TITLE
[<application>] <title>LMS mariadb upgrade issue

### ISSUE THREAD

**Issue by boaz-ng72** [bitnami/vms#1638]
### Describe your issue as much as you can

I am using LMS AWS AMI using moodle 4.0 with Mariadb 10.3.
to upgrade the moodle I must upgrade the Mariadb 
trying to upgrade it using the documents in:
https://mariadb.org/download/?t=repo-config&d=Debian+10+%22buster%22&v=11.4&r_m=truenetwork
causes the mariadb servise not to start "Failed to start mariadb: Failed to start mariadb"
in Bitnami documentation, I do not find any proceedure on how to upgrade the Mariadb.
can you please assist letting me know where can I find a resourcse, to assist me upgrade the mariadb from 10.3 to 11.4 ?

**Comment by gongomgra** [comment]
Hi @boaz-ng72,

Thanks for using Bitnami. The base components in our images like MariaDB can't be installed using that guide because they are build from source code and not installed using the official packages. You will need to launch a new instance with the updated database server and migrate the app information there

https://docs.bitnami.com/aws/how-to/migrate-wordpress/

**Comment by boaz-ng72** [comment]
@gongomgra 
thank you for the prompt reply.
does the “All-in-One WP Migration” plugin support the Bitnami LMS package as well?
Thanks

**Comment by gongomgra** [comment]
@boaz-ng72 sorry, my fault, I sent you the WordPress guide by mistake. I will update it. Please check the guide linked below

https://docs.bitnami.com/aws/how-to/migrate-moodle/

Apart from the guide above, we highly recommend you the official guides from the Moodle team on how to migrate its application data, just in case there is any additional step needed for this process to succeed.

**Comment by boaz-ng72** [comment]
perfect, I will try it.
Thank you
