### ISSUE TITLE
LAMP - MariaDB is maxing out the CPU on my EC2 instance

### ISSUE THREAD

**Issue by tooliedotter** [bitnami/vms#1645]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

It-did-not-upload-how-do-I-upload

### bndiagnostic output

    ✓ Processes: No issues found
    ✓ Mariadb: No issues found
    ? Connectivity: Found possible issues
    ✓ Php: No issues found
    ? Apache: Found possible issues
    ✓ Resources: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]
Found recent error or warning messages in the Apache error log.
```
[Wed Aug 28 02:44:13.421248 2024] [proxy_fcgi:error] [pid 89804:tid
139887504201408] [client **ip_address**:13542] AH01071: Got error 'PHP message:
PHP Warning: Undefined property: stdClass::$image_intro_alt in
/opt/bitnami/apache/htdocs/grantcountybeat.com/templates/ja_athena/html/layouts/j
oomla/content/image/intro.php on line 40; PHP message: PHP Warning: Undefined
property: stdClass::$image_intro_alt in
/opt/bitnami/apache/htdocs/grantcountybeat.com/templates/ja_athena/html/layouts/j
oomla/co [Wed Aug 28 02:44:16.175959 2024] [proxy_fcgi:error] [pid 90597:tid
139887743112896] [client **ip_address**:17354] AH01071: Got error 'PHP message:
PHP Warning: Undefined property: stdClass::$image_intro_alt in
/opt/bitnami/apache/htdocs/grantcountybeat.com/templates/ja_athena/html/layouts/j
oomla/content/image/intro.php on line 40; PHP message: PHP Warning: Undefined
property: stdClass::$image_intro_alt in
/opt/bitnami/apache/htdocs/grantcountybeat.com/templates/ja_athena/html/layouts/j
oomla/ [Wed Aug 28 02:44:16.695953 2024] [proxy_fcgi:error] [pid 90597:tid
139887445452480] (70007)The timeout specified has expired: [client
**ip_address**:53596] AH01075: Error dispatching request to : (polling)
```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-errors-apache/
Press [Enter] to continue:
===== End of bndiagnostic tool output =====`

### bndiagnostic was not useful. Could you please tell us why?

This is probably not a template issue

### Describe your issue as much as you can

MariaDB is using up all the available memory (as high as 94,4%) on a regular basis lately (see below). I'm running Joomla 5 on a LAMP stack, and I have already disabled binary logging. 

```
top - 01:25:21 up 4 days, 11:23,  1 user,  load average: 1.85, 3.15, 3.03
Tasks: 144 total,   2 running, 142 sleeping,   0 stopped,   0 zombie
%Cpu(s): 67.2 us,  6.0 sy,  0.0 ni, 26.1 id,  0.7 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  15753.8 total,   9134.2 free,   3124.9 used,   3911.0 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  12628.9 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   3734 mysql     20   0 3358768   1.1g  24280 S  94.4   7.0     86,57 mysqld
  86978 daemon    20   0  392032  95776  63000 S   6.6   0.6   0:42.73 php-fpm
  86496 daemon    20   0  305716  78448  58144 S   5.3   0.5   0:57.93 php-fpm
  86526 daemon    20   0  305600  77772  57568 S   5.3   0.5   1:03.31 php-fpm
  86376 daemon    20   0  311964  85376  58764 S   5.0   0.5   0:57.89 php-fpm
  86532 daemon    20   0  303548  75780  57576 S   5.0   0.5   0:58.46 php-fpm
  86374 daemon    20   0  303660  76024  57764 S   4.7   0.5   1:01.41 php-fpm
  86542 daemon    20   0  307692  80180  57956 S   4.7   0.5   0:58.47 php-fpm
  86525 daemon    20   0  305512  78328  58188 S   4.3   0.5   0:58.84 php-fpm
  86508 daemon    20   0  318012  90844  58244 S   4.0   0.6   1:00.61 php-fpm
  86528 daemon    20   0  303596  75928  57764 S   2.7   0.5   0:57.86 php-fpm
  86380 daemon    20   0  379720  83536  62968 S   1.7   0.5   0:59.91 php-fpm
  86262 daemon    20   0  317836  90120  57696 R   1.3   0.6   0:59.31 php-fpm
  87601 daemon    20   0 2066652  34908   8740 S   0.7   0.2   0:10.50 httpd
  77876 daemon    20   0 2065716  32924   8740 S   0.3   0.2   0:17.22 httpd
  84779 daemon    20   0 2065828  44916   8740 S   0.3   0.3   0:22.39 httpd
  86540 daemon    20   0  301564  74072  57892 S   0.3   0.5   1:01.10 php-fpm
  87000 daemon    20   0 2065552  38848   8804 S   0.3   0.2   0:15.43 httpd`
```

Two questions:

1. What else could be occupying the CPU?
2. Why is the SWAP file not being used on this instance? Can I enable that? Will it help?

**Comment by tooliedotter** [comment]
I tried to upload the diagnostic file but it's 75MB! Where do I upload it?

**Comment by gongomgra** [comment]
Hi @tooliedotter,

Can you run the bndiagnostic tool again to see if it can be uploaded this time? If the bndiagnostic file can't be uploaded because it is too big, please check our server performance troubleshooting guide

https://docs.bitnami.com/aws/faq/troubleshooting/troubleshoot-server-performance/

According to the information you shared, it looks like MariaDB is under big pressure. Notice it is not taking the memory but the CPU resources instead. You may want to temporarily enable binary logging in order to determine what's causing these errors and how to fix them.

Regarding swap memory, your server has more than enough free memory (around 9 GiB) according to the info you shared, so calling the swap memory is not necessary under those conditions.

**Comment by tooliedotter** [comment]
I can temporarily enable binary logging but I have no idea where to look and what to review. Can you please be very specific as to the location of the log and the types of entries to review?

**Comment by gongomgra** [comment]
Hi @tooliedotter,

We recommend you to check the official MariaDB documentation about binlog files and its cli tool `mariadb-binlog` in order to get more information on how to check and extract information from those files:

https://mariadb.com/kb/en/binary-log/

The files will be created under the `/opt/bitnami/mariadb` folder, likely under the `/opt/bitnami/mariadb/data`, but I'm afraid I can't confirm so. From them you would be able to evaluate the different queries that the database is receiving and other statistics like the amount of time needed to attend it.
