### ISSUE TITLE
[WordPress] Open Wordpress Page (Bitnami VM) when on a different network

### ISSUE THREAD

**Issue by RhettFinck** [bitnami/vms#1646]
### Describe your issue as much as you can

Please can you assist me, 

I have been working on a local VM with VirtualBox, and now that I am away from my home wifi network, I am unable to login to my wordpress install, please advise. The IP Range is still the same.

**Comment by jotamartos** [comment]
You will need to configure your router to allow port forwarding. You will need to look for the specific documentation of your router to configure that. 

https://learn.g2.com/port-forwarding

After configuring that, you should be able to access the app using your public IP address.

**Comment by ira6655gorby** [comment]
Here are a few potential solutions:

Check Network Configuration in VirtualBox:

Ensure that the network adapter of your VM is set up correctly. If you want to access the VM from outside your home network, you might need to use Bridged Adapter mode instead of NAT. This will allow your VM to get an IP address from your home router directly, which can then be accessed from outside your network.
If you’re using NAT mode, the VM gets an internal IP address that isn't accessible directly from outside your home network.
Remote Access Setup:

Dynamic DNS: If you’re trying to access your VM remotely, consider setting up a Dynamic DNS (DDNS) service. This will give you a consistent domain name that points to your home IP address, even if it changes.
Port Forwarding: You might need to set up port forwarding on your home router to allow external access to your VM. This involves forwarding port 80 (HTTP) and/or port 443 (HTTPS) to the VM’s internal IP address.
VPN Access:

VPN Server: If you have a VPN server set up at home, you can connect to your home network remotely and access the VM as if you were on the same local network.
VPN Client: Ensure the VPN client on your device is configured to connect to your home network.
Check Firewall and Security Settings:

Ensure that there are no firewall rules or security settings blocking access to your VM. Both the VM’s firewall and your home router’s firewall settings might need to be adjusted.
Verify IP Address:

When you’re at home, check the IP address assigned to your VM to ensure it’s reachable. You can use tools like ping or tracert to test connectivity.
Localhost Access:

If you're trying to access the WordPress installation from the same machine running VirtualBox, make sure you're using the correct address. For local access, this [NYStateofHealth](https://www.ny-stateofhealth.com/) is usually something like http://localhost:port/ or http://127.0.0.1:port/.
Access via Localhost from Host Machine:

If you have port forwarding set up correctly and can access the VM’s services via localhost from your host machine, then you might be able to use that as a temporary solution.
Consider Using a Cloud Service:

If remote access continues to be an issue, you might consider moving your WordPress install to a cloud-based VM or hosting service that offers better remote access options.
