### ISSUE TITLE
[Ghost] Incorrect password error

### ISSUE THREAD

**Issue by Reetrieve** [bitnami/vms#1651]
### Describe your issue as much as you can

Hi, I've installed the Ghost ova on Oracle's virtual box, and when I access the site via the given IP address, it takes me to the demo website. When I go to the http://localhost/ghost/#/signin (ghost admin, page shows user's blog login), and use the given username and password (user@example.com - @.aPJIL*******, it just gives an incorrect password error.

How do I access the ghost control panel to set up and design the website?

**Comment by michael569gardne** [comment]
It seems the demo site is loading instead of your setup. Check if Ghost is running correctly by visiting the IP address of your VM directly. Ensure you’re using the [ADPWorkforceNow](https://www.iadpworkforcenow.com) correct admin URL, typically `http://<your-ip>:2368/ghost/`. If login issues persist, reset the admin password using Ghost CLI commands or consult the Ghost documentation for troubleshooting.

**Comment by jotamartos** [comment]
Hi,

I just launched a fresh Bitnami Ghost VM and could login without issues in the backend (http://IP_ADDRESS/ghost)

To ensure that you are using the correct password, please access the VM's console, and run the following command 

```
sudo cat /home/bitnami/bitnami_credentials
```

https://docs.bitnami.com/virtual-machine/faq/get-started/find-credentials/

As a workaround, and if it's a fresh instance, you can try to deploy it again, just in case the deployment failed.

**Comment by Reetrieve** [comment]
I will dowonload the OVA and scrub the instance folders, and redo it from scratch. Maybe there was an issue with the downloaded OVA file. I'll get back to you, thanks.

________________________________
