### ISSUE TITLE
[<Bitnami Wordpress>] <>

### ISSUE THREAD

**Issue by alexungurasu** [bitnami/vms#1655]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4ea21767-c379-0900-f6a1-73f8a3f8bbcf

### bndiagnostic output

Startup: file created in the system's temporary directory in Unknown on line 0. referer: http://192.168.1.7/up-admin/post.php?post=7756@action elementor
[Sun Sep 08 08:28:00.161871 20241 [proxy_fcgi:error] [pid 382:tid 581] [client wip_address**:655241 AH01071: Got error 'PHP message: PHP Notice: PHP Request
Startup: file created in the system's temporary directory in Unknown on line 0. referer: http://192.168.1.7/up-admin/post.php?post=7756&action=elementor

### bndiagnostic was not useful. Could you please tell us why?

I couldn't figure out how to fix it

### Describe your issue as much as you can

My PC turned off while I was working on a page, when I turned it back on I was no longer able to reach the WordPress site.

**Comment by alexungurasu** [comment]
![Screenshot 2024-09-12 163233](https://github.com/user-attachments/assets/965fe3e8-c27f-4f06-91ff-f7df60b3fac6)
update, I solved the previous problem now I'm left with a connectivity problem

**Comment by gongomgra** [comment]
Hi @alexungurasu,

Thanks for using Bitnami. I'm glad you managed to fix your problems with the website. Those connectivity issues are shown due to some missing tools that we are no longer installing in our images by default. We will remove that check from the bndiagnostic tool. In the meantime, you can disregard those messages.
