### ISSUE TITLE
[Guacamole] latest download address

### ISSUE THREAD

**Issue by kerberos666** [bitnami/vms#1661]
### Describe your suggestion as much as you can

I saw that they removed the application and do not offer any other alternative, why?
How can I download the latest version that was released: 

Version 1.5.5-0-r05      2024-07-01
* Updated apache to 2.4.60
* Updated gdal to 3.9.1
* Updated pgbackrest to 2.52.1
* Updated tomcat to 9.0.90

**Comment by jotamartos** [comment]
Thank you for using Bitnami. We are constantly updating the catalog, adding and removing solutions from it. In this case, we removed Guacamole due to low usage reasons. 

You can still download it from here, but we won't provide support anymore https://downloads.bitnami.com/files/stacks/guacamole/1/bitnami-guacamole-1.5.5-r5-debian-12-amd64.ova

**Comment by lurume84** [comment]
> Thank you for using Bitnami. We are constantly updating the catalog, adding and removing solutions from it. In this case, we removed Guacamole due to low usage reasons.
> 
> You can still download it from here, but we won't provide support anymore https://downloads.bitnami.com/files/stacks/guacamole/1/bitnami-guacamole-1.5.5-r5-debian-12-amd64.ova

This link does not work anymore, do you have an updated one? Thanks!

**Comment by jotamartos** [comment]
Thanks for your interest but Bitnami Guacamole was deprecated and it is no longer available for download.
