### ISSUE TITLE
[bitnami/redmine] Cannot start the console

### ISSUE THREAD

**Issue by ant-222** [bitnami/vms#1685]
### Name and Version

bitnami/redmine:4.1.1-5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Launch `user_remine.bat` to enter the Redmine command line evnironment.
2. Execute `bundle exec rails c production` to lauch the Redmine Rails console.

### What is the expected behavior?

The Redmine Rails console starts.

### What do you see instead?

[These](https://pastebin.com/raw/nv2u9ya8) usage instructions for `rails new`.

### Additional information

This is not so much an assue as a help request. I cannot seem to find a way to start the Redmine Rails console for the management and administration of Redmine via the API, e.g. for user administration as described [here](https://www.redmine.org/boards/2/topics/8550). Am I doing something wrong, or is my setup somehow broken? Where can I seek help with this?

**Comment by gongomgra** [comment]
Hi @ant-222,

Thanks for using Bitnami. We dropped support for native installers back in 2022 (you can get more information in [this blogpost](https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html)). We recommend you to try to check the different log files you will find in the Bitnami installation for Apache and Redmine to determine what's the issue you are facing. We also recommend you to start the Redmine services via the control UI app you will find in the Bitnami installation instead of manually running the rails command.

Apart from the above, we highly encourage you to move to a more recent solution of the Redmine stack like the container or the OVA to benefit from the newer features and security fixes that both the application and other components like Ruby or Apache may have released since your application was installed. Notice you are using a version that was released [back in 2020](https://bitnami.com/stack/redmine/vboxdebian-x64-nami/changelog.txt).

https://bitnami.com/stack/redmine

Hope it helps!

**Comment by ant-222** [comment]
@gongomgra, You clearly did not understand my specific problem and my solution to it. I need the Ruby Redmine for much more than starting the services. I will consider using a new version of your Redmine package.

**Comment by gongomgra** [comment]
@ant-222 I'm afraid there's not much we can do here. As mentioned in my previous message you are using an old solution that we don't support. Unfortunately, it is not possible to upgrade the base components in you current installation either. We recommend you to launch a newer version of the Bitnami Redmine virtual-machine and migrate your application data there.
