### ISSUE TITLE
Install WordPress in Subdirectory Bitnami AWS Lightsail

### ISSUE THREAD

**Issue by dangerdon78** [bitnami/vms#235]
### Describe your issue as much as you can

I have a WordPress site want to migrate to AWS bitnami lightsail.

I just installed the WordPress on root. it's working.
I want to know how to Install WordPress in Subdirectory Bitnami AWS Lightsail.
127.0.0.1 [Root WordPress Done]
127.0.0.1/blog/ [Sub Directory Wordpress] Need help.

**Comment by gongomgra** [comment]
Hi @dangerdon78,

Thanks for using Bitnami. You can follow the steps in our guide on how to add a custom PHP file on your server.

https://docs.bitnami.com/aws/infrastructure/lamp/administration/create-custom-application-php/

Also the `Alias` directive will help you to define the `/blog` path.

**Comment by Caterinaside** [comment]
Amazon Lightsail provides WordPress blueprints that you can use to launch and start using the WordPress application. This WordPress application is packaged by Bitnami. Instead of using this Bitnami stack, you can install WordPress manually in your Lightsail OS instances, such as Amazon Linux 2, Ubuntu, CentOS, and so on. The following resolution covers the steps for installing WordPress in the major Linux distributions available in Lightsail.

[MyLabCorp Employee Login](https://www.mylabcorp.us/)
