### ISSUE TITLE
[bitnami aws lightsail wordpress multisite] Upgrade PHP to 7.4

### ISSUE THREAD

**Issue by confidentcyber** [bitnami/vms#277]
### Describe your issue as much as you can

Is there a how-to guide for updating PHP for wordpress multisite?

**Comment by nccerhostmaster** [comment]
Although it's possible to do this, it's not supported, and not a good idea to try it unless you like lots of manual troubleshooting and configuration fiddling. 

The fastest and easiest approach for upgrading a Bitnami Wordpress image in Lightsail is to deploy a new Bitnami instance with newer software, then migrate your content over from the old instance, either manually or using one of the various Wordpress migration tools available.

**Comment by nccerhostmaster** [comment]
Here is the procedure I use to update a Lightsail Wordpress site:

- If the site does not already have a static IP address in Lightsail, I will first apply a static IP the original Wordpress site, update DNS, and wait for propagation.
- Create a snapshot of the current site in case something goes wrong
- Upgrade the existing Wordpress and any plugins as much as possible on the old instance
- Verify functionality at each step
- Create a new Lightsail instance with more recent software (Lightsail Bitnami instances are designed for stability, and won't have the latest bleeding-edge versions) 
- Backup the existing wordpress site content and database, either manually, or using one of the Wordpress migration products available, such as Duplicator
- Using the hosts file on my computer, or a browser plugin or local DNS, point the original domain name to the new instance address
- Verify functionality at each step
- Apply the backups to the new instance
- Verify functionality
- Once the site is working properly, go into Lightsail and remove the static IP from the original site and apply it to the new site
- Remove hosts file entry or browser plugin settings, restart browser, and verify functionality of the new site

Depending on the complexity of your site, the process can be done in as little as an hour. You'll probably spend a lot longer trying to upgrade PHP in place, and it probably won't be supported.

The need to occasionally refresh a Lightsail instance with a new Bitnami version to get newer software is one of the down sides to using Lightsail. That's why I generally only use the Bitnami instances for sites that I know will either be redesigned/rebuilt frequently or are for temporary use. 

For sites that I know will be maintained and updated extensively for years, I use an OS-only instance and install components manually instead.
