### ISSUE TITLE
Change Parse Server Version

### ISSUE THREAD

**Issue by LoganLC** [bitnami/vms#301]
### Describe your issue as much as you can

Following the steps in the documentation found here: https://docs.bitnami.com/general/apps/parse/administration/upgrade/ I get the error:

Refusing to install package with name "parse-server" under a package also called "parse-server". Did you name your project the same as the dependency you're installing?

I would like to change my parse server version to @4.10.14 so I am following the steps and typing - npm install parse-server@4.  How can I achieve this?

Thank you

**Comment by gongomgra** [comment]
Hi @LoganLC,

Thanks for your message. I was able to reproduce your issue. It looks like the npm tool itself prevents now installing the same package into the same directory, however I was able to install latest version by updating the `package.json` file with the latest one from Github (version 5.2.5 now), removing the `package-json.lock` file (if present) and then running `npm install`. I also had to update the parse URL in the new `config.json` file. Can you try these steps on your side? 

We highly recommend you to create a server backup before running any command on your server so you can easily restore it.

**Comment by LoganLC** [comment]
Hi @gongomgra

I can't find the 5.2.5 version.  Can you link it please?

Thanks,
Logan

**Comment by gongomgra** [comment]
Hi @LoganLC,

You can find it in their official Github repository

https://github.com/parse-community/parse-server/releases/tag/5.2.5

**Comment by LoganLC** [comment]
Hi @gongomgra 

Unfortunately this did not work for me.  As mentioned I am looking to install parse 4.10.14.  I replaced the package.json with the 4.10.14 version.  I then deleted the package-lock.json, ran npm install and updated my server URL in config.json.  However now parse-server will not start.  I keep getting - Error: Cannot find module 'mustache'.

Any other suggestions?

Thanks,
Logan

**Comment by gongomgra** [comment]
Hi @LoganLC,

Sorry, I misread your message and missed you are trying to use a different major version (`4.x` instead of `5.0`). Changing between major versions may lead to errors due to the different requirements for each version. According to our registries, the latest Parse 4.x image we released was for version `4.1.0-0`, and after that we started offering 5.x images only. 

You can find version `4.1.0-0` in the AWS EC2 Community AMIs. If you are using a virtual machine locally, you can download the `4.10.7-3` version using the next link

https://downloads.bitnami.com/files/stacks/parse/4.10.7-3/bitnami-parse-4.10.7-3-linux-centos-7-x86_64-nami.ova

 You can try to launch it and follow the upgrade process (it contains a previous NPM version), or try the same approach I suggested here (updating the version in the `package.json` file and installing dependencies). If it doesn't work either, I'm afraid you will need to find another way of running Parse 4.10.14. We provide this version in our [containers solutions](https://github.com/bitnami/containers/tree/main/bitnami/parse), in case it is a good fit for you.

**Comment by LoganLC** [comment]
Hi @gongomgra 

I appreciate your response. I used the community version and tried both approaches to update and neither worked.  At this point I am not confident this configuration will ever be able to be updated.  Will changes be made to the naming so we can update in the future?

Also, I am having trouble accessing my mongo shell.  Can you please provide the commands to do so as the ones here (https://docs.bitnami.com/general/apps/parse/get-started/connect-mongodb/) do not work

Thank you

**Comment by LoganLC** [comment]
Hi @gongomgra,

Thanks for the mongo command - it worked.  

Regarding the install, I don't believe parse will be able to help me as this configuration is unique to the bitnami stack.  In the example you posted, parse-server is simply a package that is part of a bigger project (I have a similar set up on my local machine and have no issues updating with npm).  In the bitnami stack however it seems like parse server is the entire package.json but the opt/bitnami/parse directory is different then the default parse-server configuration.  I am not super familiar with server side stacks but there must be a way bitnami updates its stacks with every release of parse server.  If you figure it out could you please let me know.

Thank you,
Logan

**Comment by gongomgra** [comment]
Hi @LoganLC,

Thanks for your message. Instead of upgrading the components of our stacks, although possible in most of the cases, we recommend to start a new server with the new version and components, and then migrate the application data. 

Unfortunately, we didn't release cloud images for the Parse server version you are looking for, but we released it in our [containers repository](https://github.com/bitnami/containers/tree/main/bitnami/parse). We suggest you to deploy the container on your server and migrate the application data.
