### ISSUE TITLE
[wordpress] A definition of a siteurl or homeurl was detected in your wp-config.php, but the file is not writable.

### ISSUE THREAD

**Issue by MDOT77777** [bitnami/vms#304]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2c1ad607-24e6-58bd-956b-f1570bceed7d

### bndiagnostic output

    ? Apache: Found possible issues
    ✓ Mariadb: No issues found
    ✓ Connectivity: No issues found
    ? Wordpress: Found possible issues
    ? Resources: Found possible issues
    ✓ Processes: No issues found
    ✓ Php: No issues found

### bndiagnostic was not useful. Could you please tell us why?

Didn't identity the main issue 

### Describe your issue as much as you can

We have an issue with our Wordpress website url https://www.pbtgroup.com.au/ it encountered the issue that we need to setup the wp config.php to be writable and reload the page can you please assist with that?

![image](https://user-images.githubusercontent.com/112690004/188393843-4af115d9-1266-42fb-8aa3-5c15368055a9.png)

**Comment by gongomgra** [comment]
Hi @MDOT77777,

That should be a new feature in the latest version. Please update the file permissions to 664 for `/bitnami/wordpress/wp-config.php`, reload your dashboard. Once WordPress has updated the file, we recommend you to set back the 640 permissions for security reasons.

**Comment by mukatrpetra** [comment]
> Hi @MDOT77777,
> 
> That should be a new feature in the latest version. Please update the file permissions to 664 for `/bitnami/wordpress/wp-config.php`, and then reload your dashboard. Once WordPress has updated the file, we recommend you to set back the 640 permissions for security reasons.

@gongomgra Kindly let me know how to update the wp-config.php file permissions to 664, because bitnami tutorial video regarding to this problem is expired, you can find the view in this [link](https://docs.bitnami.com/aws/how-to/troubleshoot-wordpress-issues/)
and this is the direct [video link](https://www.youtube.com/watch?v=ceKD-WgJXBc&list=PLGgVZHi3XQNn4x0DU7Qj1r_inej3xEUda)

I tried a lot to change the permission but nothing changed, wp-config.php file look like to be just a shortcut from the original file which existed in wordpress/wp-config.php

> Size : | 4 KB
> Path : | wordpress/​wp-config.php
> Link : | wp-config.php
> Modified : | Aug 20, 2022 08:25 AM
> Permissions : | read
> Locked : | no

**Comment by gongomgra** [comment]
Hi @mukatrpetra,

You just need to run the `chmod` command against the `/bitnami/wordpress/wp-config.php` file

```
sudo chmod 664 /bitnami/wordpress/wp-config.php
sudo chmod 640 /bitnami/wordpress/wp-config.php
```
