### ISSUE TITLE
[wordpress] how to change The Default Administrator Email of wordpress bitnami aws lightsail > from (user@eample.com) to my email address

### ISSUE THREAD

**Issue by Shadman-sahi** [bitnami/vms#316]
### Describe your issue as much as you can

how to change The Default Administrator Email of WordPress bitnami aws lightshail > from (user@eample.com) to my email address

**Comment by Shadman-sahi** [comment]
please help anyone

**Comment by gongomgra** [comment]
Hi @Shadman-sahi,

Thanks for using Bitnami. You can update the email address from the WordPress admin panel interface or directly from the database (you will have to SSH connect to your server). WordPress usually send a confirmation email when you try to update the user email, and because the default value is a non-valid email address, we recommend you to update the value directly from the database.

We also recommend you to create a server backup before performing any change to the database, so you can easily restore it. If you have any doubt on how to update the database value, please open a new question in the official WordPress forums

https://wordpress.org/support/forums/
