### ISSUE TITLE
[TensorFlow Serving] Unable to test resnet

### ISSUE THREAD

**Issue by tillal** [bitnami/vms#329]
### Describe your issue as much as you can

I might not be in the right place but I'm unable to see where to ask for help. I just installed version 2.9.1 and unfortunately I cannot even perform a test by calling resnet_client_cc.

Please see below steps to reproduce 

- Login to gcloud instance
- Then get an image to test 
```
cd /tmp
curl -LO 'https://tensorflow.org/images/blogs/serving/cat.jpg'
```

- Then run a test by using the following command
```resnet_client_cc --image_file=cat.jpg```

Instead of receiving the correct information, I get the below
```
calling predict using file: cat.jpg  ...
gRPC call return code: 14: failed to connect to all addresses
gRPC failed.
```
Any idea what I have done wrong?

Thank you

**Comment by gongomgra** [comment]
Hi @tillal, 

Thanks for using Bitnami. I launched a fresh new server and reproduced your issue. I found out that the default model [mentioned in our "test image recognition" guide](https://docs.bitnami.com/aws/infrastructure/tensorflow-serving/configuration/test-image-recognition/) is not configured in Tensorflow's config file at `/opt/bitnami/tensorflow-serving/conf/tensorflow-serving.conf`, and it is generating the next warning message in the Tensorflow Serving logs

```
2022-09-13 09:44:55.468141: W tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:252] No versions of servable resnet found under base path /bitnami/model-data. Did you forget to name your leaf directory as a number (eg. '/1/')?
```

I edited the config file to update the `base_path` key to `/opt/bitnami/model-data` and restarted the service (`sudo /opt/bitnami/ctlscript.sh restart`), and then tested the `cat.jpg` image again, but it returned a different error.

```
$ $ resnet_client_cc --image_file=./cat.jpg
calling predict using file: ./cat.jpg  ...
gRPC call return code: 3: input tensor alias not found in signature: input_1. Inputs expected to be in the set {image_bytes}.
gRPC failed.
```

According to this [thread in the official Github repo](https://github.com/tensorflow/serving/issues/1947), this can be caused by an old version of the models. Can you try using a different model? Unfortunately, I don't have enough knowledge on how Tensorflow works to suggest you a different model or version.

**Comment by brujbaur** [comment]
Does Bitnami actually support their product?  I have installed and tried to get the tensorflow serving AMI working as well, the same errors received here, the same attempts to fix it with the same bad results.  Please provide a solution to this unworkable offering, or perhaps remove it from your catalog.

**Comment by gongomgra** [comment]
@brujbaur I have reproduced your issue and I have found a solution. Let's continue checking it on your other thread

https://github.com/bitnami/vms/issues/1662
