### ISSUE TITLE
[LAMP] How to update/upgrade Linux VM (Lightsail)

### ISSUE THREAD

**Issue by FastEddieAustin** [bitnami/vms#380]
### Describe your issue as much as you can

I have discovered a LightSail VM that appears to have been built in the distant past by a former employee with the LAMP option so it is running an ancient version of Ubuntu.  (New instances seem to run Debian despite Amazon saying Ubuntu on their site.)  

From looking at the handful of posts here the common feedback is you have to provision a new VM and then restore your data.  I must be missing something...why can't an OS update, which I think should upgrade all of the components like PHP, MySQL, etc., be used to maintain the LIghtsail VM?

**Comment by jotamartos** [comment]
Hi @FastEddieAustin,

We do not use the system packages or the system's package manager (apt) to build and run our VMs. We build the components from scratch and that's why the `apt upgrade` or `apt install` commands doesn't upgrade PHP or MySQL. If you want to upgrade the base components, you need to launch a new instance and migrate your data.
