### ISSUE TITLE
[Google launchpad] Can i use E2 machine on GCP?

### ISSUE THREAD

**Issue by Yossifsolman** [bitnami/vms#416]
Hello everybody, i see in GCP marketplace and in the Bitnami lunch pad N1 machines and not got any suggestion for E2 machine
(the compute optimize machines of GCP)

N1 is first generation, when E2 is second generation, much newer.

Have reason for that?
Bitnami can work with E2 machines?

-----

Another funny thing ( little out of this topic, but i will try to get all the answer i can in one post )

Why don't have Redis?
**Nginx and Redis in one installation can boost Bitnami to another levels.**

If i want to install Redis. Have some Bitnami docs for it?
I see have some article about that in docs.bitnami.com
but none of them actually shows how to deploy Redis on deployment via GCP.

**In general, the docs not show so much about GCP, or how to optimize the 4 packages you offered on GCP.
( like Lite Speed WordPress, for example ).

Be happy if someone will light me the subject.

**Comment by gongomgra** [comment]
Hi @Yossifsolman,

Thanks for using Bitnami. I've just tried to launch a fresh new server using our launchpad for Google cloud and both the e2 and n2 instances were listed for me. I selected many different regions and e2 instances were listed in all of them. Can you tell us which region where you using? Can you also share an screenshot with us?

![Screen Shot 2022-10-19 at 09 29 17](https://user-images.githubusercontent.com/6660452/196635279-80461d28-a18b-462e-92ea-bc76b5f37ec5.png)

**Comment by Yossifsolman** [comment]
Its not what i actully asked.

Ok for example if you choose another product (not Bitnami)
you will see the default option of machine a little different.

Uselly when the "Developer" (you in this case)
put as default N1 machine as default machine for his platform, have reason for that.

This is the reason i asking right now this thing.
If Bitnami default  (N1 machine) better for Bitnami?
Or
Bitnami can be used on E2 machine as well?


---------------------------


The must important is Redis, be happy if you can answer me how to install it properly (RPM - Repo of Bitnami i believe).
As i said in my previous messages, i see a lot of articles in Bitnami.com but none of them actually shows the proper way
to install Redis on Bitnami.

In general, the docs not show so much on the product and how to improve / control him properly on GCP.

**Comment by gongomgra** [comment]
Hi @Yossifsolman,

Sorry, I misunderstood your message. We are probably selecting N1 instances by default because they fit our memory requirements better than E2 instances (default memory requirement is usually 512 MB for NGINX), and smaller E2 instances series is 1 GB. Another reason can be that N1 micro instance (our default) is less expensive than E2 instances for a micro instance type. That said, our images should be able to work on any instance type you chose. Notice the instance type just depends on your specific use case. The default instance type is mean to cover most of the "let's give it a try" cases.

Regarding NGINX + Redis, I'm afraid we don't provide any solution with these two components. Unfortunately, after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term. We apologize for the inconvenience.

It is also not possible to install Bitnami Redis on top of your Bitnami NGINX image. As an alternative, you can run our [redis container](https://github.com/bitnami/containers/tree/main/bitnami/redis) on your instance and use it as any other service of your development machine. You can also manually install Redis from system package manager using `apt-get`.
