### ISSUE TITLE
How Do I: Update Instances With Updated AMIs? - LAMP packaged by Bitnami

### ISSUE THREAD

**Issue by ryanallandorn** [bitnami/vms#438]
Hi there, I use [LAMP packaged by Bitnami](https://aws.amazon.com/marketplace/pp/prodview-6g3gzfcih6dvu#pdp-usage) rather frequently & often get emails titled **_"Product Update: Upgrade to LAMP packaged by Bitnami new version"_** & in the email there's a bit: 

> However, Bitnami by VMware does recommend you to update to the latest version, LAMP packaged by Bitnami/7.4.32-3-r03 on Debian 11 by visiting [https://aws.amazon.com/marketplace/pp/prodview-6g3gzfcih6dvu](https://v8xqhkq3.r.us-east-1.awstrack.me/L0/https:%2F%2Faws.amazon.com%2Fmarketplace%2Fpp%2Fprodview-6g3gzfcih6dvu/1/010001840085b50a-35ca05c5-92cb-47c8-88ab-9ae26670c0ee-000000/lfBwGWKu7XCZ0j9aObLOXleG54M=292).  

...the link in the above email excerpt just takes be back to the AWS AMI profile page, though (i.e. what I'm expecting is: some context on how to actually update)

My issue is: 

- Basic - I know - but _how do I update my instances with updated AMI_?  (Or put differently, what is the best way to efficiently manage updating my instances with updated AMIs?)
- Ideally, I want to be able to update my instances with new AMI versions without having to do a bunch of snapshots, etc

To be more specific, I have looked at:
- [Patching Amazon Machine Images](https://docs.aws.amazon.com/systems-manager/latest/userguide/automation-walk-ami-patching.html)
- Is patching & using the `AWS-UpdateLinuxAmi` runbook what I even need to be doing? [Walkthrough: Patch a Linux AMI (console)](https://docs.aws.amazon.com/systems-manager/latest/userguide/automation-walk-patch-linux-ami-console.html)
- Are there any kinds of update scripts that I just don't know about?
- Would it just be easier to go through the changelogs and update the various packages myself via SSH & `apt`?

**Comment by gongomgra** [comment]
Hi @ryanallandorn,

Thanks for using Bitnami. I'm afraid I don't know how those tools from the AWS team work. You will have to ask the AWS support team about them. I also understand these emails you mention are sent by AWS when we publish a new image, suggesting you to use the latest image available, but notice it is not a requirement, as included changes may not affect you.

From our side, we recommend launching a fresh new image including updated components from our installation (Apache, MariaDB, PHP...), and then migrate your applications and data to the new instance. Unfortunately, it is not possible to update our components individually, because they are built together to ensure compatibility. Regarding the system packages (updated with the `apt-get` tool), you can install the [unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades) packages to get the latest security updates automatically, or manually update them according to your own policies.
