### ISSUE TITLE
Bitnami blocking Elementor 

### ISSUE THREAD

**Issue by keun1702** [bitnami/vms#476]
### Platform

Installers

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

.

### bndiagnostic output

I work on localhost with bitnami. I downloaded Elementor but to view the website the loading screen doesn't work. I contacted Elementor, they checked the System info file. 
After a few tests, they concluded that Bitnami does not work with the Elementor plugin. 

They wrote me: 
"It seems that this error is related to your server blocking the connection with the Elementor server.
Please get in touch with Bitnami to find out if they are blocking Elementor on their servers. In case they are, they will need to whitelist:
elementor.com
my.elementor.com"

Anyone who can help me? How can I contact Bitnami for this?

### bndiagnostic was not useful. Could you please tell us why?

.

### Describe your issue as much as you can

I work on localhost with bitnami. I downloaded Elementor but to view the website the loading screen doesn't work. I contacted Elementor, they checked the System info file. 
After a few tests, they concluded that Bitnami does not work with the Elementor plugin. 

They wrote me: 
"It seems that this error is related to your server blocking the connection with the Elementor server.
Please get in touch with Bitnami to find out if they are blocking Elementor on their servers. In case they are, they will need to whitelist:
elementor.com
my.elementor.com"

Anyone who can help me? How can I contact Bitnami for this?

**Comment by gongomgra** [comment]
Hi @keun1702,

Thanks for using Bitnami. We are not internally blocking any domain in our installations. Can you give us more information about your issue? Which kind of our WordPress stack are you using (installer, OVA, cloud image, container, etc)? Which version? 

Can you run the bndiagnostic tool and share the generated code with us so we can take a look to your installation logs? Can you also check the Apache logs for any error with the elementor plugin?

**Comment by keun1702** [comment]
Dear @gongomgra 
Thanks for your help.

I'm sorry, but I can't manage to run the Bitnami Diagnostic tool. Can you help me with this? Or is there perhaps an instructional video available?

What i’m using:
- Installer on localhost
- Elementor Pro v3.8.1

Thank you inadvance.

**Comment by keun1702** [comment]
Dear @gongomgra 

You can forget the above comment. I managed to run the diagnosis. See the code below:
c60b1ccb-56c6-ea51-a7d0-6dce4f26ac3c

I await your response.

**Comment by gongomgra** [comment]
Hi @keun1702, @EPROM-RSA,

Thanks for your messages. @keun1702 it looks like your bndiagnostic bundle doesn't include the Apache logs, which are the key to continue debugging your issue. Can you check them? It is located at `INSTALLDIR/apache2/logs/error_log`

@EPROM-RSA regarding your bnsupport bundle, I see the next error message multiple times in the Apache log

```
[Fri Nov 11 11:14:35.328792 2022] [mpm_winnt:notice] [pid 5416:tid 416] AH00354: Child: Starting 64 worker threads.^M
VirtualProtect() failed [87] The parameter is incorrect
```

Can you update the Apache `LogLevel` in the `httpd.conf` file setting it to `debug`, and then restart the Apache service? After that, please check the error log for a more verbose error. Notice letting the `LogLevel` set to `debug` will make the `error_log` file size to increase rapidly, so we recommend to restore the previous default value once you have checked the updated error message. Remember you need to restart the service for changes to take effect.

Additionally, can you double-check your Elementor version is compatible with the included components in your installation?

**Comment by keun1702** [comment]
[error.zip](https://github.com/bitnami/vms/files/9993035/error.zip)
@gongomgra thanks for your message. See attachment. Hopefully I did it right?

**Comment by EPROM-RSA** [comment]
Today uninstall / complete new install Bitnami 6.1-0   WP6.1-0   Elementor 3.8.0   Woocommerce 7.1.0
set LogLevel  debug     change post-max-size 512M  upload-max-filesize  512M    Restart Servers
Delete ALL plugins   Install All-in-one 7.5   Inport the Exported file from https://bke.co.za  ( all plugins work ok here )  
Deactivate local ALL plugins   site works as expected
Activate 1 plugin at time Form 7 OK , All-in-one OK , Woocommerce OK ,  Elementor ERROR
Activate F7 AIO WC together  OK  
Elementor allone or in combination with any of the others  ERROR
Run diagnostics with only Elementor active   ba7bf09d-fdf4-4624-812e-d8462768db59

Running diagnostics created Avast alarm see attached.
My gut feeling tells me there is a problem between Bitnami and Elementor because Elementor works fine on my website.

[error.zip](https://github.com/bitnami/vms/files/9994661/error.zip)
![Elementor-Active-Error](https://user-images.githubusercontent.com/57669235/201468110-86a4c061-a3ad-4d97-bf38-76e5d3e5db9e.jpg)
![Avast-Threat](https://user-images.githubusercontent.com/57669235/201468119-4de472b1-234f-4756-9345-d30cd6fcb8f1.jpg)

**Comment by EPROM-RSA** [comment]
Today did clean install of BN 6.1-0 , default Theme , removed all plugins , installed Elementor 3.8.1 free version.
try Visit Site ........   The connection was reset   ... Error  same screen as attached 2 days ago

**Comment by keun1702** [comment]
> [error.zip](https://github.com/bitnami/vms/files/9993035/error.zip) @gongomgra thanks for your message. See attachment. Hopefully I did it right?

Dear @gongomgra ,
Did you already checked the attachment with the apache logs?

**Comment by gongomgra** [comment]
Hi @keun1702,

Thanks for your message. Yes, I downloaded the log file, and I found the same error message than in @EPROM-RSA's plus a couple of other messages related to the elementor-pro plugin. Can you check it with the plugin developers?

```
[Fri Nov 11 20:56:57.309792 2022] [php:warn] [pid 17432:tid 1200] [client ::1:60290] PHP Warning:  Undefined array key "requires" in C:\\Bitmany\\apps\\wordpress\\htdocs\\wp-content\\plugins\\elementor-pro\\license\\updater.php on line 69, referer: http://localhost/wordpress/wp-cron.php?doing_wp_cron=1668196609.7791380882263183593750^M
[Fri Nov 11 20:56:57.309792 2022] [php:warn] [pid 17432:tid 1200] [client ::1:60290] PHP Warning:  Undefined array key "new_version" in C:\\Bitmany\\apps\\wordpress\\htdocs\\wp-content\\plugins\\elementor-pro\\license\\updater.php on line 84, referer: http://localhost/wordpress/wp-cron.php?doing_wp_cron=1668196609.7791380882263183593750^M
VirtualProtect() failed [87] De parameter is onjuist
```

@EPROM-RSA I also see an error in your WordPress cronjobs, but in your case it doesn't seem to be specific to the elementor-pro plugin 

```
[Sat Nov 12 10:45:55.997431 2022] [php:notice] [pid 13056:tid 1180] [client 127.0.0.1:63115] Cron reschedule event error for hook: action_scheduler_run_queue, Error code: invalid_schedule, Error message: Event schedule does not exist., Data: {"schedule":"every_minute","args":["WP Cron"],"interval":60}, referer: http://127.0.0.1/wordpress/wp-cron.php?doing_wp_cron=1668242755.9317939281463623046875^M
```

**Comment by gongomgra** [comment]
I did a new test and I didn't find any error with the Elementor website builder plugin. I launched a fresh new container with latest WordPress version and activated the Elementor plugin without issues. Then, I edited the hello-world post using it and it worked just fine.

![Screen Shot 2022-11-14 at 13 31 50](https://user-images.githubusercontent.com/6660452/201660974-bce74dd1-dc60-47de-8a3e-0c68aec7d50e.png)

Notice we can't test the elementor-pro plugin as it is a premium plugin. You will have to contact the plugin developers for further help on this.

**Comment by gongomgra** [comment]
Hi @EPROM-RSA,

I was able to reproduce the issue on a Windows machine using the latest installer. I could install and activate the Elementor plugin, but I found the same `VirtualProtect() failed [87] The parameter is incorrect` error when trying to use it.

![Screen Shot 2022-11-17 at 13 48 56](https://user-images.githubusercontent.com/6660452/202507128-d49876a9-59ac-4400-b89b-2fe9be241ebe.png)

However, I was not able to get any other information from the logs, so I can't tell if it is an issue with the PHP binary we use in our installation (from [php.net](https://www.php.net/downloads.php)) or with WordPress/Elementor.

Can you try to reproduce it with our virtual machine? 

https://bitnami.com/stack/wordpress/virtual-machine

Notice we will discontinue the support for all native installers by November 30th, 2022. You can get more information about this in the next blog post

https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html

**Comment by EPROM-RSA** [comment]
Hi Gonzalo

Tried to install VM on W10 system but have no clue what the Error means or how to correct it.
This totally new territory for me

**Comment by gongomgra** [comment]
Hi @EPROM-RSA ,

Thanks for your message. Please find below our guide on how to get started with our virtual machines.

https://docs.bitnami.com/virtual-machine/get-started-virtualbox/

Hope it helps!

**Comment by maxrys** [comment]
About `virtualprotect() failed 87 the parameter is incorrect`

I was investigating the same case.

I tested CMS EFFCORE on the Windows platform (`Windows 10 2021 LTSC x64`).

After installing Apache House (`httpd-2.4.57-win64-VS17.zip`) and PHP (`php-8.2.11-vs16-x64.zip`), I began to include the missing modules to install the system.

I enabled all the required modules and the system installed without problems.

I ran all the tests and they ran successfully.

Then I decided to speed up the system and enabled `OPCache + JIT`.

After enabling `OPCache + JIT` I started getting a "white screen" and the message `virtualprotect() failed 87 the parameter is incorrect`.

After disabling `OPCache + JIT` or `OPCache` the problem went away.

I was wondering what this error was.

I created a small script and placed it in the `test.php` file.

It had the following contents:

    $path = 'data.php';
    $lines_num = 2000;
    if (!file_exists($path)) {
        file_put_contents($path, '<?php'."\n", FILE_APPEND);
        for ($i = 0; $i < $lines_num; $i++)
            file_put_contents($path, '$data['.$i.'] = \'value '.$i."';\n", FILE_APPEND);
        file_put_contents($path, 'print \'COUNT: \'.count($data);', FILE_APPEND);
        print 'FILE WAS CREATED. RELOAD THIS PAGE';
    } else {
        include_once($path);
        print "\n".'FILE WAS INCLUDED';
    }

Next, I ran `test.php` from the browser and got a white screen if `lines_num` was greater than `2000` and a normal result if less than `2000`.
This is an obvious _overflow of some memory segment_.
However, the log did not contain any information about the error.

From the console I ran this script with any number of `lines_num` and no problems arose.

    php -d opcache.jit_debug=1 test.php
    php -d opcache.jit_debug=1 data.php

I concluded that the problem is with the Apache + PHP combination as a module.
However, there were no problems under Linux/Unix.

Here is the complete list of links:
- win: Apache + PHP as a module - `JIT problem`
- win: IIS + PHP as FastCGI - OK
- win: PHP CLI - OK
- nix: Apache + PHP as a module - OK
- nix: NGINX + PHP as FastCGI - OK
- nix: PHP CLI - OK

I had to disable OPCache in `php.ini` via `opcache.enable=0` and the problem went away.

In `php.ini` you can disable only `JIT` via `opcache.jit_buffer_size=0` but this setting cannot be changed directly from PHP code.

Changing other `opcache.*` settings in `php.ini` did not lead to anything.

You can also disable `OPCache + JIT` programmatically with the following code:

     if (DIRECTORY_SEPARATOR === '\\') {
         ini_set('opcache.enable', false);
     }

Thank you for your attention, I hope it helped.

**Comment by gongomgra** [comment]
Hi @maxrys,

Thanks for checking this issue and for sharing your solution! I'm sure it will be of help to other users in the future.
