### ISSUE TITLE
[<application>] <title>

### ISSUE THREAD

**Issue by Lou-1SE** [bitnami/vms#48]
### Describe your issue as much as you can

Hi, I have installed the bitnami wordpress multisite locally on my computer. (MacBook Pro 8-Core Intel Core i9, running macOS 11.6). I am running the normal Bitnami Wordpress no problem. I just would like to get the multisite working. Where do I find the multisite user name and password please? (My other bitnami/ wp passwords don’t work) 
I tried to download the bitnami diagnostic tool to see if it could help me but I can’t find where to do this to help me? 
I have tried to restarting, waiting to all the multisite service buttons are green and opening terminal and running the command: cat ~/bitnami_credentials  - but no matter how many times I do this it doesn't work as it comes back to say -  no such file or directory.
Thanks :)

**Comment by jotamartos** [comment]
Hi @Lou-1SE,

I'm glad to hear you managed to get the password. Instead of running the SSH command, you can open the VM's terminal using the OS X VM user interface

https://docs.bitnami.com/installer/faq/osx-vm-faq/administration/access-console-osx-vm/

and then run the `cat` command to get the password of the solution 

```
cat ~/bitnami_credentials
```

Thanks

**Comment by Lou-1SE** [comment]
Hi @jotamartos,
Yes I had tried that a few times with no success unfortunately (I had opened this issue on the bitnami help page a few weeks earlier and I couldn't find a resolution until a few days ago)
Thanks for your advice what to do though :)
