### ISSUE TITLE
Why is there no longer a windows download, rather than a virtual machine? I want my copy LOCAL[<application>] <title>

### ISSUE THREAD

**Issue by DrewShults** [bitnami/vms#578]
### Describe your issue as much as you can

It's getting annoying constantly being forced to put everything on the cloud. I don't want it on the cloud and I don't want it on a virtual machine. Why in the world is there suddenly no longer an install package for local windows version? Can I PLEASE get a Window install download link for local Bitnami since it doesn't exist on your site? Thank you.

**Comment by gongomgra** [comment]
Hi @DrewShults,

Thanks for your interest in using Bitnami. Unfortunately, we stopped providing the local installers in favor of our containers, virtual machines and cloud images offering. You can get more details on this by checking our blogspot entry linked below.

https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html

We can still provide you with the Windows installers we already published (notice it may contain old versions of the different components included). Is there any specific application and version we can share with you?

**Comment by pionsys-mha** [comment]
Hi @gongomgra,

I ran into the same issue with the following Redmine installation:

Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.1.9-p490 (2016-03-30) [i386-mingw32]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.14.1
  Filesystem                     
Redmine plugins:
  no plugin installed

Can you please provide the latest Windows installer to me which can be used in order to update the existing installation of Redmine to your latest one? Which steps are to-be-performed in order to keep the current database also after the update?
We might take a look onto your VM based solutions in future, but for the current case I would like to avoid this step. Which steps are to-be-performed in order to bring our current database into the VM?


Thanks in advance,
    Markus

**Comment by gongomgra** [comment]
Hi @pionsys-mha,

Thanks for using Bitnami. It doesn't seem clear to me that the issue you are posting is fully related to this topic. Anyways, if you are trying to update a Redmine installation from such an old version (from 2016), we recommend you to ask in the official Redmine forums for help on this, just in case upgrading two major versions in one step is not possible. In case you need any previous version of our solutions to perform your upgrade, please open a new thread asking for it, in order to avoid mixing different topics here. 

Apart from the above, using the virtual-machine instead of the Windows installer shouldn't imply any change in the application or database usage processes (commands for exporting/importing a database are the same). The only major differences between both solutions is that the virtual-machine is based on Linux.

**Comment by pionsys-mha** [comment]
Hi @gongomgra,

thank you for these explanations. When we have to perform the same steps for the upgrade from the old version to the latest Windows variant like we would need for the update to your VM based solution, we probably will (have to) move to the VM based solution directly.

Best Regards,
    Markus

**Comment by gongomgra** [comment]
Hi @pionsys-mha,

Thanks for your message. We hope you can upgrade to the latest Redmine version available.

**Comment by jnowak123** [comment]
Hi @gongomgra if its's possible I'm interested in gaining access to the already published Windows installers. I understand the most recent version you published is 6.1.1-0.

**Comment by gongomgra** [comment]
@jnowak123, thanks for your message. I don't know to which asset to you are referring to, can you clarify? Per the version you shared I guess you mean WordPress, so I'm sharing the download link below just in case.

https://downloads.bitnami.com/files/stacks/wordpress/6.1.1-0/bitnami-wordpress-6.1.1-0-windows-x64-installer.exe

However, please note **we highly recommend you to use our virtual-machine solution** instead of the local installer. Also take into account that the local installer includes old versions of its included components that may be affected by security issues.

**Comment by jnowak123** [comment]
@gongomgra Thanks a ton! 
I'm using this in conjunction with simply static to create pages for netlify and it's the simplest solution for creating and hosting free websites I've found, so security shouldn't be an issue.

**Comment by gongomgra** [comment]
Hi @jnowak123,

Thanks for your message. I'm glad it worked for you. As an alternative to the no longer supported local installers, we also recommend you to check our containers solutions, which are officially supported by the team. You can check it in the next link

https://github.com/bitnami/containers/tree/main/bitnami/wordpress

**Comment by klopotnik** [comment]
hi.. i am looking for something specific 
redmine 3 package for ubuntu, with ruby 2.3 version
do you have something like that please still available? local installation
(i know it is many years old, but i need it for few days running again)

**Comment by klopotnik** [comment]
sorry, close this, i will open new issue :)

**Comment by gongomgra** [comment]
Hi @klopotnik,

Thanks for letting us know. I'm closing this ticket.

**Comment by RaddyS** [comment]
Hey Guys, thank you for having this link  https://downloads.bitnami.com/files/stacks/wordpress/6.1.1-0/bitnami-wordpress-6.1.1-0-windows-x64-installer.exe as some projects still need doing on local PC and without the need for VM or cloud virtualization. I agree that the rest is cool and needed even easer but some times old-school is needed too.

**Comment by RaddyS** [comment]
Do you guys have a link for local version multisite?

**Comment by gongomgra** [comment]
Hi @RaddyS,

Thanks for using Bitnami. We no longer provide local installers, only virtual machines, containers, Helm charts and cloud images. You can download the latest virtual-machine from our website

https://bitnami.com/stack/wordpress-multisite/virtual-machine

Hope it helps

**Comment by NikoNemo** [comment]
Hello Bitnami,

Can you please share WordPress local install for Linux/Ubuntu?!
Thanks!

**Comment by gongomgra** [comment]
Hi @NikoNemo,

Thanks for your interest in using Bitnami. As mentioned previously, we no longer provide support for local installers, only virtual-machines. You can download it from our website

https://bitnami.com/stack/wordpress/virtual-machine
