### ISSUE TITLE
  I need to change the PHP of my aws lightsail instance. Can you guide me, please.

### ISSUE THREAD

**Issue by CarlosBrandaoBeC** [bitnami/vms#581]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

afb7cb51-d13c-8e0e-9287-3a8a0aa3bb65

### bndiagnostic output

total used free shared buff/cache available Mem: 990 513 81 74 396 168 Swap: 
634 608 26

### bndiagnostic was not useful. Could you please tell us why?

Yes

### Describe your issue as much as you can

Good morning people! Is everyone okay?
I really need help, I have a single wordpress and I need to update my PHP version from v7.3.14 to higher than this because my wordpress is demanding to see images and besides I can't access the wordpress admin anymore because of this error that is giving in the image, can you help me, please?
![Captura de Tela 2023-01-04 às 07 39 42](https://user-images.githubusercontent.com/54544830/210543208-f970e131-2a67-4a54-82e4-d878eddcb7b9.png)

**Comment by mdhont** [comment]
Bitnami applications come preconfigured and ready to use, and use their own components rather than relying on system components. As a result, it is not possible to update components individually. I recommend launching the latest version of the Bitnami application which uses the latest component's versions and then migrate your WordPress site there using the All-in-one migration plugin.
