### ISSUE TITLE
Bitnami install on windows fails when there's an existing MySQL instance for another app.

### ISSUE THREAD

**Issue by billharrelson** [bitnami/vms#617]
### Describe your issue as much as you can

We run a Windows server with multiple vhosts and are trying to install a bitnami WAMP stack.  One of the other vhosts uses Moodle with it's own MySQL installation.  When we try to install bitnami, despite giving different names, the installation always fails when it tries to connect to the second MySQL to create the initial user.  Can't find a resolution for this anywhere on the web, and not sure this is the right place.  Both MySQL services are running.
Thanks for any direction you can give.

**Comment by gongomgra** [comment]
Hi @billharrelson,

Thanks for using Bitnami. Did the installation of the WAMP stack detect that another server was using MySQL port 3306 and asked you to select another port? Can you check the installation logs? Can you try to manually connect to the second server using the command line and the root user? The password should be the one you provided during the installation process.

The installation log file should be located under the `%TEMP%` folder.

Apart from the above, we highly recommend you to migrate to out virtual-machine solution for LAMP instead of continue using the local installers. We have recently deprecated the local installers in favor of our virtual machines, cloud images, and containers solutions.

https://blog.bitnami.com/2022/11/focusing-on-cloud-native-solutions.html

**Comment by billharrelson** [comment]
Hi @gongomgra,
Thanks for answering.  Yes, it detected it, and we entered the other port (3307), it always failed on trying to create the initial user.  MySQL at the command line succeeded with the --port option.  We finally got it to work by stopping the other MySQL, installing in the default way, and then changing configurations to use 3307 after the second installation was complete.  This is a Windows machine, not Linux, and the server is shared with other domains and systems.  Virtual machine solutions are not an option.

**Comment by gongomgra** [comment]
Hi @billharrelson,

Thanks for your message. I'm glad you managed to fix your issue! As mentioned in my previous message, we no longer support local installers, so we won't be able to provide a solution for similar (or new) issues in the future.
