### ISSUE TITLE
Bitnami-lampstack-7.1.16-0 upgrade to supported version.

### ISSUE THREAD

**Issue by mmtriny** [bitnami/vms#633]
### Describe your issue as much as you can

We have Ubuntu 18.0 VM in AWS where we have been running a self-installed WordPress website. 

The instance was originally installed with bitnami-lampstack-7.1.16-0 and WordPress. 
WordPress is up to date.
PHP is out of date on version 7.1. I believe since this was installed as a lamp stack, it's incredible difficult (or impossible) to upgrade PHP without installing a new stack. 
 
I noticed there is no longer any Bitnami documentation for self-hosted/native setups. There are also no downloadable links to get the latest linux-x64-installer.run if you want to do a manual install. 

I would like to get PHP upgraded from V7.1 so that my WP website is secure. 

what are my options to get PHP upgraded?

**Comment by mdhont** [comment]
Bitnami applications come preconfigured and ready to use, and use their own components rather than relying on system components. As a result, it is not possible to update components individually. We recommend launching a new Bitnami LAMP instance, which comes with the latest component versions, and then migrate your app there.
