### ISSUE TITLE
[Joomla] Server error when uploading file

### ISSUE THREAD

**Issue by muktadey-sen** [bitnami/vms#662]
### Describe your issue as much as you can

Hi recently migrated data from Existing Instance to new bitnami joomla Instance.  But when i am trying to upload a new file I am having folowing error. Could you please help me to solve it.

![image](https://user-images.githubusercontent.com/60453079/217068480-8cea9fc0-38c7-47fb-b52f-cc375112125b.png)

**Comment by jotamartos** [comment]
That's an app-related error. I suggest you take a look at the Apache's logs file (/opt/bitnami/apache2/logs) and review the Joomla's documentation and forum to see how to solve the errors. 

If the issue is related to permissions, please remember to give daemon write permissions in the Joomla's folder

```
sudo chown -R bitnami:daemon /opt/bitnami/joomla /bitnami/joomla
sudo chmod -R g+w /opt/bitnami/joomla /bitnami/joomla
sudo chmod g-w /opt/bitnami/joomla/configuration.php
```

Note: I remove write permissions to the configuration file to avoid security issues. If you require the conf file to be writable by the daemon group (Apache and PHP), do not run the last command.

**Comment by jotamartos** [comment]
As I mentioned above, that seems to be an app-related error. I suggest you take a look at the Apache's logs file (/opt/bitnami/apache2/logs) and review the Joomla's documentation and forum to see how to solve the errors. You can also contact the Joomla's support team to get more information about how to debug that error in the app's side.

**Comment by muktadey-sen** [comment]
Hi Juan,

I checked permissions for each files and read the documentation and forums. I tried trobleshooting.  still I am not finding exact cause. Could you please let me know your further advice and how to communicate with Jommla community?

![image](https://user-images.githubusercontent.com/60453079/217630149-6030aece-ac73-4835-aa9d-cdc275622c76.png)
![image](https://user-images.githubusercontent.com/60453079/217630355-f9793834-3ec0-40a9-8a0c-0cb0069cff8f.png)

**Comment by jotamartos** [comment]
From the screenshots, you are getting "memory exhausted" errors. That means that PHP doesn't have enough memory to perform the operation. It probably is due to 2 reasons:

- Increase the memory_limit parameter in the /opt/bitnami/php/etc/php.ini and restart all the services
- Ensure your machine has enough RAM memory to allocate that amount of memory. If not, you will need to increase the memory of the machine.

**Comment by muktadey-sen** [comment]
Hi Juan,
Thank you so much for your response. This machine already has 4gb RAM, and memery_limit Increased 256M to 1024M. But still having same error..

![image](https://user-images.githubusercontent.com/60453079/217958212-1a1f186c-a5dd-461e-9835-916315f56600.png)

**Comment by jotamartos** [comment]
I do not see any "memory exhausted" error now so the change seems to work. However, there are still some app-related errors. You will need to ask in the Joomla! forums to get more information about them 

https://forum.joomla.org/

**Comment by muktadey-sen** [comment]
Hi Juan,

I didn't find any option to post new questions to their forum, I am looking
for your further assistance.

[image: image.png]



Thanks
Mukta

**Comment by jotamartos** [comment]
You need to register and create a new topic under the correct category.

**Comment by muktadey-sen** [comment]
Hi Juan,
I have tried all possible ways to create new issues on the support portal,
I have my account there. But there is no option for me.

However, I believe you still can help me: Here is the specific error for
JMedia upload.

[image: image.png]

Thanks
Mukta Dey

**Comment by jotamartos** [comment]
Hi @muktadey-sen,

I can't see the image because you sent it using the email instead of uploading it directly to the Github's ticket. However, as I mentioned before, you should contact Joomla!'s developers to get more info. I do not know why you can't create a ticket there but I can't provide help with that.

**Comment by jotamartos** [comment]
That's not an error, it's just information regarding the Apache's process. Please look for errors in the log or contact Joomla!'s support team to know how to investigate this error in the application.
