### ISSUE TITLE
[Guacamole] VMware VM how to update application

### ISSUE THREAD

**Issue by asldkfj** [bitnami/vms#692]
### Describe your issue as much as you can

Looking to see how I can update the guacamole application from the Bitnami VMware image.

**Comment by jotamartos** [comment]
You will need to follow the official guidelines to upgrade the application to the latest version. However, you can also launch the latest version of the Bitnami Guacamole solution and migrate the data from your current deployment to the new one.

**Comment by asldkfj** [comment]
Ok thanks jotamartos.

I think the non-standard paths and use of postgres breaks the upgrade scripts I was pointed to.

**Comment by jotamartos** [comment]
In that case, have you tried migrating the database and the data of your application to a new deployment?

**Comment by cboling2** [comment]
Sorry to re-open this, but I'm not finding the documentation to assist with this. I installed a Bitnami Guac 1.3 VM image some years ago, and successfully upgraded Debian from 10 to 11 then 12, and it continues to work fine -- but would like to upgrade Guac and don't see any instructions on how to do it in a Bitnami distro.

Taking the other approach, I created a new VM using the current 1.5.4 image, and did a complete replacement of the /bitnami dir with the copy from the old VM, but Tomcat throws a 404 error when trying to display the default page.

**Comment by jotamartos** [comment]
There is no information regarding the upgrade process in the official documentation 

https://guacamole.apache.org/doc/gug/

but I understand you need to create a backup of the database 

https://docs.bitnami.com/general/infrastructure/postgresql/administration/backup-restore-postgresql/

and migrate all the specific files you created since the app was created and the backup you just took to a new server with the latest version of the application. 

If you have more questions, I suggest you ask the official developers of the application to get more information.
