### ISSUE TITLE
[WordPress] Site went blank after i activated a plugin fish-and-ships

### ISSUE THREAD

**Issue by modollarpo** [bitnami/vms#713]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4e3b190b-343e-b14e-01f3-617de4f42c6d

### bndiagnostic was not useful. Could you please tell us why?

it still didn't solve the issue

### Describe your issue as much as you can

Hi, I added a plugin (fish-and-ships) and it shut down the site. I've tried to disable all plugins via Bitnami but it's not shutting them all down so I can reaccess the site and delete the bad plug in and restore the site. I tried the command line here the code i got using the bitnami dianostic tool 4e3b190b-343e-b14e-01f3-617de4f42c6d but it returned an error message and I don't what else to try.

**Comment by jotamartos** [comment]
Hi,

I found errors related to the plugin you mentioned in the information the bndiagnostic got

```
Error: Fatal error: Uncaught Error: Call to a member function check_wpml() on null in /bitnami/wordpress/wp-content/plugins/fish-and-ships/fish-and-ships.php:2859
Stack trace:
#0 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(308): wocommerce_fish_n_ships_shipping_init()
#1 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#2 /opt/bitnami/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
```

You have different options here: 

- Remove the plugin in the /opt/bitnami/wordpress/wp-content/plugins folder
- The wp-content folder is currently a symlink, you can try moving it and see if the error is solved after that

https://github.com/bitnami/vms/issues/23#issuecomment-1143966330

- If you continue running into issues with the plugin, please contact the plugin's developers. This issue is out of the scope of this support forum.
