### ISSUE TITLE
[Subversion] Can't access repository from browser

### ISSUE THREAD

**Issue by bdunsmuir** [bitnami/vms#736]
### Describe your issue as much as you can

I have followed the instructions listed here: https://docs.bitnami.com/google/how-to/use-svn/. I am installing from google cloud.

When I get to step 4 to verify the repository can be reached from the browser, it asks for my username and password.
Once I enter these, I get an error that says: 

"Not Found
The requested URL was not found on this server."

I can navigate to the main IP, but as soon as I add the  /subversion to the end, it is not found. I've tried deleting the installation and redoing, but get the same problem.

I'm not sure what I'm doing wrong here. I thought this was a packaged image that wouldn't need much edits?

**Comment by jotamartos** [comment]
Hi @bdunsmuir,

Sorry for the delay. I just found the problem in the documentation and will work on updating it. Basically, the problem is that the "Location" block must be configured inside the /opt/bitnami/apache/conf/vhosts folder instead of in the /opt/bitnami/apache/conf/httpd.conf file. 

```
bitnami@debian:/opt/bitnami/apache/conf/vhosts$ cat subversion-vhost.conf
<VirtualHost 127.0.0.1:80 _default_:80>
  ServerName www.example.com
  ServerAlias *
  <Location />
    DAV svn
    SVNPath "/opt/bitnami/repository"
  </Location>
  <Location /subversion>
    DAV svn
    SVNPath "/opt/bitnami/repositories/myapp"
    AuthType Basic
    AuthName "Subversion repository"
    AuthUserFile /opt/bitnami/repositories/users
    require valid-user
  </Location>
</VirtualHost>
bitnami@debian:/opt/bitnami/apache/conf/vhosts$ cat subversion-https-vhost.conf
<VirtualHost 127.0.0.1:443 _default_:443>
  ServerName www.example.com
  ServerAlias *
  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"
  <Location />
    DAV svn
    SVNPath "/opt/bitnami/repository"
  </Location>
  <Location /subversion>
    DAV svn
    SVNPath "/opt/bitnami/repositories/myapp"
    AuthType Basic
    AuthName "Subversion repository"
    AuthUserFile /opt/bitnami/repositories/users
    require valid-user
  </Location>
</VirtualHost>
```

Once you configure it and restart Apache, you can access your new repo without problems

<img width="497" alt="Screenshot 2023-03-14 at 08 57 01" src="https://user-images.githubusercontent.com/8791635/224933203-729c9d83-8147-40b9-a6a9-3e6ecb8b95e4.png">

**Comment by jotamartos** [comment]
Just for the record, the guide in our documentation is now updated 

https://docs.bitnami.com/google/how-to/use-svn/

**Comment by bdunsmuir** [comment]
Thank you, Juan.
