### ISSUE TITLE
[WordPress] Converter for Media plugin for WP cannot be installed

### ISSUE THREAD

**Issue by gearcs** [bitnami/vms#737]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

na

### bndiagnostic was not useful. Could you please tell us why?

it's not about bitnami

### Describe your issue as much as you can

Hello, I'm trying to install 'Converter for Media' WP plugin but I'm getting this error.

It appears that your server does not support using .htaccess files from custom locations, or it requires additional configuration for the plugin to function properly.

If you are using the Apache server, this issue is usually related to the virtual host settings in the Apache configuration. Substitute the AllowOverride None value with AllowOverride All in the <Directory>...</Directory> section of the relevant .conf file for your VirtualHost. In this case, please, contact your server administrator.

---

Error codes: rewrites_not_executed

Please advise??

**Comment by jotamartos** [comment]
htaccess files are disabled by default in the Bitnami solutions due to security and performance reasons. You can learn more about that here

https://docs.bitnami.com/general/apps/wordpress/administration/use-htaccess/

You can disable that configuration (AllowOverride) in the WordPress' conf files (/opt/bitnami/apache/conf/vhosts/ directory) or follow the instructions we provide in that guide to move the .htaccess information to the .conf file.

**Comment by gearcs** [comment]
Hello there,

Thanks for your help. Can you advise which file should I change?

Basically, we need to make this php file 'wp-config.php' editable as it has
only read permission.

Please advise,

**Comment by jotamartos** [comment]
>Thanks for your help. Can you advise which file should I change?

As I mentioned, you need to edit the WordPress' files inside the /opt/bitnami/apache/conf/vhosts/ directory (wordpress-vhost.conf and wordpress-https-vhost.conf files).

Regarding the permissions, you can run the commands in this other post to reset the permissions configuration 

https://github.com/bitnami/vms/issues/22#issuecomment-1143906974

Note: You can skip the last command if you want WordPress to be able to edit the wp-config.php file.

**Comment by adam-ah** [comment]
@jotamartos I'm trying my very best to stay polite, but this is probably the worst decision any engineer could have made when creating a common image that end-users should be able to use.

Not only the site you linked is lacking crucial information, this kills many of the essential wp plugins. *For instance, you should spell out how to enable .htaccess again*

And no, it's not the fault of the users - me, being an engineer, still cannot for my life figure out why certain plugins are not loading. An average geek trying to use your image? Guaranteed failure.

Unfortunately, users will blame Lightsail, WP, or the plugin-creators for the never-ending problems *you* caused.

There is a balance between security and usability. Currently, you pulled it all the way to security.

Sure, it's easy to secure a site when cache doesn't work, when images are not loading any more, etc. etc.

Again, please undo this setting as soon as possible. In it's current state, bitnami's WP image is a dumpster fire (to put it very very politely).

**Comment by jotamartos** [comment]
Hi @adam-ah, 

Thank you for your feedback, it's really important for us. We set the AllowOverride parameter to None due to security and performance reasons, it's part of the good practices of Apache. However, we understand the issues it generates with some plugins/themes in WordPress. I'm going to share this information with the team to re-evaluate the configuration. 

As you may know, you can change that configuration in our containers and chart for WordPress. The `WORDPRESS_HTACCESS_OVERRIDE_NONE` env var allows you configure the AllowOverride parameter if needed.

https://github.com/bitnami/containers/tree/main/bitnami/wordpress#user-and-site-configuration

Again, thanks for the feedback. We will update this ticket when having more information.
