### ISSUE TITLE
[Redmine] Issue with abnormal web page after installing Windows package.

### ISSUE THREAD

**Issue by sj1027** [bitnami/vms#771]
### Describe your issue as much as you can

Hello,
I have a problem that I can't solve, so I'm contacting you for help.

After installing the latest version of the Redmine package for Windows, 
which is the "bitnami-redmine-5.0.3-0-windows-x64-installer.exe", 
when I try to access http://127.0.0.1/, an abnormal web page is displayed as shown in the attached image.

Normally, "@@BITROCK_APPLICATION_ORIGINALNAME@@" should be displayed as "Redmine". How can I solve this issue?

![image](https://user-images.githubusercontent.com/35683052/225847431-83d2c27f-317b-49e5-a713-7ab1d61b8a33.png)

**Comment by jotamartos** [comment]
That's because the installation didn't finish correctly. You can find more information about the error in the %TEMP% directory of your machine. Please ensure you have enough RAM memory and disk space available during the installation. I also suggest you use the Bitnami virtual machine for Redmine to get the latest updates.

**Comment by sj1027** [comment]
Hello,
Thank you for your response.

I have filtered the Bitnami Redmine-related log files from the %TEMP% directory you mentioned and attached them as a file. Additionally, I have also included the specifications of my laptop below. Can I identify the reason why the installation was not completed successfully through these materials?

I will wait for your response.
Thank you.

[bitnami_log.zip](https://github.com/bitnami/vms/files/11012939/bitnami_log.zip)

CPU :	12th Gen Intel(R) Core(TM) i7-1260P   2.10 GHz
RAM	16.0GB(15.7GB Available)
Device ID	84747A75-4605-43ED-825C-AADBEB5007F3
Product ID	00325-96353-10706-AAOEM
System	64 bit OS, x64 Processor

**Comment by sj1027** [comment]
I would like to add a comment. 
I tried installing it on a different laptop, not the one that had problems, and it installed successfully. Even though that laptop had lower performance than mine, it still worked well. 
I'm very curious about what the difference could be.

if we had to pinpoint one difference, it would be that on your laptop, you had performed other tasks while on the laptop where the installation worked well, no other tasks were performed besides the installation itself.

**Comment by jotamartos** [comment]
I think the issue is related to the locale configuration in your machine. Is there any difference between both computers? 

Please note that Bitnami installers are not supported anymore and, as I mentioned above, we suggest you use the Bitnami VMs to deploy this solution.

**Comment by sj1027** [comment]
As mentioned in the previous comment, it seems that the only difference between the two laptops is the version of Windows they are running. The normal laptop has a shorter installation time, while the abnormal laptop takes a very long time, approximately 3-4 hours.

Although VM distributions are only available for Debian, you need a Windows version, which is why you are attempting to install it in this manner.

**Comment by jotamartos** [comment]
There should be something wrong with the environment, or the network because the installation shouldn't take 3-4 hours. You can take a look at the installation log to see what the installer is doing, but it's probably installing gems during all that time. You will need to investigate the issue if you want to use the installer.

As an alternative, you can copy the installation directory from one machine to the other (using the same path and stopping the services in advance) and execute the serviceinstall.bat script (serviceinstall.bat INSTALL) to install the scripts in the new machine.

**Comment by sj1027** [comment]
I have successfully installed the Redmine package for Windows on a Windows 11 environment. The difference from the previous method was that I ran the "bitnami-redmine-5.0.3-0-windows-x64-installer.exe" file as an 'administrator.' I'm not exactly sure why, but I'm happy that the installation went smoothly. Thank you for your support so far.
