### ISSUE TITLE
[Wordpress] Certified by Bitnami and Automattic 6.1.1-43

### ISSUE THREAD

**Issue by Taufiqs95** [bitnami/vms#787]
### Describe your suggestion as much as you can

hello bitnami

1. I have successfully installed wordpress WordPress Certified by Bitnami and Automattic 6.1.1-43 but I found an error with my theme having an error like the image below
`https://prnt.sc/oBa5nW4aZJlE`
Here's a screenshot from another server using the same theme I used. see picture below.
`https://prnt.sc/IFoOiSA7YmM3`

2. If I use Nginx Packaged by Bitnami 1.23.3-20. My theme is normal. when I install the W3 total cache cache, there is a notification that I restart Nginx and it won't go away. 
I followed this guide Install WordPress On Top Of The Bitnami NGINX Stack
`https://docs.bitnami.com/aws/how-to/install-wordpress-nginx/

How to properly install Nginx-Wordpress+W3 Total Cache like the WordPress Certified by Bitnami and Automatti package as above, admin.

Please provide me a solution so that I can quickly migrate to my new aws server.
Thank You
`

**Comment by jotamartos** [comment]
Hi,

This is a plugin-related issue so we suggest you ask in the official forums of WordPress or to the plugin's/theme's developers to know more about it. 

Please note that this issue is out of the scope of this forum. However, we suggest you take a look at these guides to know how to reconfigure the permissions or enable .htaccess in case the plugin/theme requires it. 

https://github.com/bitnami/vms/issues/23
https://github.com/bitnami/vms/issues/3
https://docs.bitnami.com/general/apps/wordpress/administration/use-htaccess/

**Comment by Taufiqs95** [comment]
hello [jotamartos](https://github.com/jotamartos)
well if this theme of mine has a problem in its development plugin.

The next step, I want to ask how to install Wordpress + NGINX + W3 Total Cache or FastCGI, please tell me a tutorial on how to install it correctly and complete the tutorial, if possible look for videos or articles 

Thank You

**Comment by jotamartos** [comment]
We do provide a WordPress with NGINX solution so you do not need to install WordPress on top of NGINX by your own. However, the guide you posted above explains how to install WordPress on top of the NGINX stack. 

Regarding the plugin, we have [a generic guide](https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/optimize-bitnami-wordpress/) in our documentation. However, as I mentioned above, if you get any error when installing the plugin, you should contact the plugin's developers or its guides to know how to troubleshoot it.
