### ISSUE TITLE
[WordPress Production-Ready] CloudFormation problem

### ISSUE THREAD

**Issue by brunoleyne** [bitnami/vms#796]
### Describe your suggestion as much as you can

I tested and tried to use version 6.1.1-4-r03 on Debian 11 (Nov 29, 2022) and is not working because of the problem with the parameter [DBStorageEncrypted] do not exist in the template. I checked cloudformation template and this parameter is not there like old versions, maybe someone forgot to add there. 
I would suggest to release another version of this pack more up-to-date.
Another issue that I found is that the guide to configure varnish is broken for this configuration: https://docs.bitnami.com/aws-templates/apps/wordpress-production-ready/configuration/configure-varnish/

**Comment by jotamartos** [comment]
Hi @brunoleyne,

Sorry for the delay here. We tested the solution on our side and it passed the tests successfully. However, it seems there was a problem on the AWS side when copying the templates to the Marketplace and that's why the solution is failing during the launch process. 

However, we decided to drop support for this solution and the rest of available MultiTier solutions in the AWS Marketplace so we suggest you launch any other Bitnami WordPress solution in AWS. 

Regards.
