### ISSUE TITLE
[Guacamole] after restart of VM I get an internal error while opening a session 

### ISSUE THREAD

**Issue by testtobi** [bitnami/vms#813]
### Describe your issue as much as you can

Used version:
 bitnami-guacamole-1.5.0-6-r08-linux-vm-debian-11-x86_64-nami

Setup: 
the mentioned version is used as a jump host, to have access to all VMs (via RDP, VNC or SSH) at the connected system.
The VM is hosted on a server running ESXi 7, but the following issue also appears in VirtulBox. The VM has two network interfaces every one with its own IP range. One for the connection to the system and a second one where the WebUI is reachable via LAN.

Issue: 
I can configure the VM that everything is reachable and every session can be opened successfully, no matter which protocol.
The problem appears after a reboot of the VM. If I try to open a session e.g. via SSH or RDP I get the following error: "An internal error has occurred within the Guacamole server, and the connection has been terminated. If the problem persists, please notify your system administrator, or check your system logs."

I am not very familiar in which log I can find any hint why I get this error message after a reboot.

**Comment by testtobi** [comment]
Additional Information:
Steps I did to configure the VM for my situation:
configure the network interfaces (IP addresses)
configure the connections

**Comment by testtobi** [comment]
Solution which works fine for me:
If this issue appears, a restart of the guacamole-server via the ctlscript.sh helps to fix it.
-> I added a service within systemd which restarts the guacamole-server right after the bitnami service is finished.

Nevertheless, a reason for this issue would be good to know.

**Comment by jotamartos** [comment]
Hi @testtobi,

I just tried to reproduce the issue but couldn't do so. I restarted the VM and the application continued working properly. This issue is probably related with your environment so you will need to get more information about the error. There should be more information in the Guacamole's log file or the Tomcat's one.

Regards

**Comment by endiz** [comment]
> Solution which works fine for me: If this issue appears, a restart of the guacamole-server via the ctlscript.sh helps to fix it. -> I added a service within systemd which restarts the guacamole-server right after the bitnami service is finished.
> 
> Nevertheless, a reason for this issue would be good to know.

Do you mind posting your restart service config? I got the same issue with guac failing to connect to server, but running "sudo /opt/bitnami/ctlscript.sh restart" solved the issue so i want to run it after the bitami service as well.

**Comment by endiz** [comment]
I believe its related to the guacamole-server service starting before the postgresql service has loaded properly. When the issue happens, the guacamole-server service is stopped, and doesn't come back up using the "/opt/bitnami/ctlscript.sh restart guacamole-server" command. Only way to bring everything back up is running "/opt/bitnami/ctlscript.sh restart" which restarts everything.

In the logs i see errors related to authentication:

`21:36:06.396 [http-nio-8080-exec-6] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
21:36:06.396 [http-nio-8080-exec-6] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
21:36:06.707 [http-nio-8080-exec-6] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
21:36:06.707 [http-nio-8080-exec-6] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
21:36:14.615 [http-nio-8080-exec-8] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
21:36:14.616 [http-nio-8080-exec-8] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
21:36:14.626 [http-nio-8080-exec-8] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.
21:36:14.627 [http-nio-8080-exec-8] WARN  o.a.g.e.AuthenticationProviderFacade - Authentication attempt ignored because the relevant authentication provider could not be loaded. Please check for errors earlier in the logs.`

I'm using the bitnami azure marketplace VM with a Standard_B1ms size.

Hope that helps, thanks for the support.
