### ISSUE TITLE
[<bitnami wordpress drupal joomla mariaDB>] <WP, Joomla, Drupal on same mariaDB>

### ISSUE THREAD

**Issue by plhmk** [bitnami/vms#864]
### Describe your issue as much as you can

I am trying to create 3 containers (Drupal, Joomla and WordPress) who work with the same and with the same DB of mariaDB
Attached yml file, but don't work
Error message is: error on connecting on mariaDB
Someone can help me were is wrong ?
Thanks, regards
[compose.zip](https://github.com/bitnami/vms/files/11280454/compose.zip)

**Comment by gongomgra** [comment]
Hi @plhmk,

Thanks for using Bitnami. This is the forum for cloud images and virtual machines support. Please open a new ticket in the container's repo for your question.

Also please share the content of the `docker-compose.yaml` file directly in the new thread, instead of sharing it as a zip file. It will make easier for the team to understand and review your scenario.

https://github.com/bitnami/containers/issues
