### ISSUE TITLE
Bitnami Roundcube OVA

### ISSUE THREAD

**Issue by witzker** [bitnami/vms#882]
### Describe your issue as much as you can

I have set up Bitnami Roundcube OVA on my tiny ESXi 7 server
as far I can see - all went Ok
I open the Application with the IP shown - OK

BUT

![image](https://user-images.githubusercontent.com/4120266/235343556-b8b47795-69d6-4969-9d33-00864310ce33.png)
I cannot log in with bitnami / bitnami

![image](https://user-images.githubusercontent.com/4120266/235343873-44f43172-9bbc-4c56-9fdf-c0322b8d1b29.png)

![image](https://user-images.githubusercontent.com/4120266/235343922-78a3e709-6ec3-46d6-a919-294883f0edcf.png)

 
What have I done wrong?

I think after reading some instructions, my approach to log in with "bitnami " as shown above is WRONG!!

and also described here:
![image](https://user-images.githubusercontent.com/4120266/235368776-4ce340ea-12c0-454c-b208-38970cf74b0c.png)

Now I used a Gmail address, "myadress@gmail.com"
and Password witch worx to login @gmail

BUT same 

![image](https://user-images.githubusercontent.com/4120266/235343922-78a3e709-6ec3-46d6-a919-294883f0edcf.png)

**Comment by gongomgra** [comment]
Hi @witzker,

Thanks for using Bitnami. Yes, the Roundcube application works with your custom email address and password for the third-party service (Google's gmail on your case). I'm afraid I don't know if you would need to allow the ["less secure APPs" setting](https://support.google.com/accounts/answer/6010255?hl=en) in your Google account in order to allow the Roudcube-Gmail connection. Please note **we do not recommend you to enable that setting**, it is just an idea of what can be your issue.

We recommend you to open a new question in the official Roundcube forums for further help on this.

https://www.roundcubeforum.net/
