### ISSUE TITLE
[bitnami/wordpress] downgrade php version

### ISSUE THREAD

**Issue by srakl** [bitnami/vms#892]
### Describe your issue as much as you can

How do i downgrade my php version from php 8 to php 7? 

I found this

https://docs.bitnami.com/aws/apps/wordpress-multisite/configuration/install-modules-php/

but can't find the steps to do so. did i miss something? thanks

**Comment by mdhont** [comment]
Bitnami applications come preconfigured and ready to use, and use their own components rather than relying on system components. As a result, it is not possible to update components individually.

**Comment by srakl** [comment]
so I can't downgrade the php version on aws ec2 / bitnami?

**Comment by mdhont** [comment]
No, unfortunately that is not possible. Perhaps this needs some further explanation. Bitnami applications are designed to utilize the latest components, and all components are preconfigured for ease of deployment. This approach adheres to best practices for security since we use the latest versions of each component, making it more difficult for hackers to exploit known security vulnerabilities in older components. As PHP 7 has already reached the end of its active support, Bitnami no longer maintains it.

**Comment by mdhont** [comment]
Unfortunately that is not possible. Bitnami applications are designed to utilize the latest components, and all components are preconfigured for ease of deployment. This approach adheres to best practices for security since we use the latest versions of each component, making it more difficult for hackers to exploit known security vulnerabilities in older components. As PHP 7 has already reached the end of its active support, Bitnami no longer maintains it.
