### ISSUE TITLE
[Wordpress] Redirect www to no-www

### ISSUE THREAD

**Issue by y-chen** [bitnami/vms#926]
### Describe your issue as much as you can

Hi all,

I have a Wordpress website running on AWS Lightsail and I have to set a redirect from www version of the website to no-www. How can I do it?

For the moment I tried to edit `/opt/bitnami/apache2/conf/httpd.conf` and add configuration like 

```
RewriteEngine On
RewriteCond %{HTTP_HOST} ^www\. [NC]
RewriteRule ^(.*)$ http://example.com/$1 [L,R=301]
```

But it didn't work.

I tried different version from many websites like 

https://www.sminrana.com/uncategorized/bitnami-wordpress-redirect-www-to-non-www/
https://linuxhandbook.com/redirect-www-to-non-www/
https://codingwithcody.com/2019/07/26/redirects-on-aws-lightsail-wordpress/

But none of these worked.

What am I doing wrong?

Thank you

**Comment by gongomgra** [comment]
Hi @y-chen,

Thanks for using Bitnami. You also need to update the WordPress specific configuration in order to redirect www to non-www domain. You can find all the required steps in our guide linked below

https://docs.bitnami.com/aws/apps/wordpress/administration/redirect-custom-domains/#redirect-wwwmyappexamplecom-to-myappexamplecom

Hope it helps!

**Comment by y-chen** [comment]
Hi @gongomgra ,

it worked like a charm.

Thank you for the support.

**Comment by gongomgra** [comment]
Hi @y-chen,

Thanks for your message. I'm glad it worked for you!!
